import { StyleSheet } from '@react-pdf/renderer';
import { CST, DOCUMENT } from '@/lib/brand';

// PDF usa pontos, não pixels. 10,5pt no corpo equivale a 14px a 96dpi.
// Superfícies sólidas e hairlines traduzem o vidro sem prejudicar a impressão.
export const estilosPdf = StyleSheet.create({
  pagina: {
    paddingTop: 68,
    paddingBottom: 62,
    paddingHorizontal: 46,
    backgroundColor: DOCUMENT.paper,
    color: CST.navy,
    fontFamily: 'GeistPdf',
    fontSize: 10.5,
    lineHeight: 1.5,
  },
  cabecalho: {
    position: 'absolute',
    left: 46,
    right: 46,
    top: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.6,
    borderBottomColor: DOCUMENT.line,
    paddingBottom: 10,
  },
  cabecalhoTitulo: { fontSize: 9, color: DOCUMENT.body },
  metadado: { fontSize: 8, color: DOCUMENT.faint },
  rodape: {
    position: 'absolute',
    left: 46,
    right: 46,
    // A4: ancorar pelo topo evita que o rodapé saia da página no wrapping do React-PDF.
    top: 791,
    borderTopWidth: 0.6,
    borderTopColor: DOCUMENT.line,
    paddingTop: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: DOCUMENT.faint,
  },
  fornecedor: { fontSize: 10, color: DOCUMENT.body, marginBottom: 10 },
  titulo: {
    fontSize: 29,
    fontWeight: 600,
    lineHeight: 1.14,
    letterSpacing: -0.65,
    marginBottom: 12,
  },
  subtitulo: { fontSize: 11, color: DOCUMENT.body, marginBottom: 12 },
  destinatario: { marginBottom: 22 },
  rotulo: { fontSize: 9, color: DOCUMENT.faint },
  empresa: { fontSize: 12, fontWeight: 600, marginTop: 3 },
  contato: { fontSize: 9, color: DOCUMENT.body, marginTop: 2 },
  investimento: {
    padding: 20,
    backgroundColor: DOCUMENT.soft,
    borderWidth: 0.7,
    borderColor: DOCUMENT.line,
    borderRadius: 12,
    marginBottom: 16,
  },
  investimentoTopo: { flexDirection: 'row', justifyContent: 'space-between', gap: 16 },
  valorGrupo: { flexGrow: 1, flexShrink: 1 },
  valor: {
    fontFamily: 'GeistMonoPdf',
    fontWeight: 500,
    fontSize: 23,
    marginTop: 5,
    lineHeight: 1.25,
  },
  validade: { width: 72, flexShrink: 0, alignItems: 'flex-end' },
  validadeValor: { fontSize: 12, marginTop: 9 },
  condicoes: { fontSize: 10.5, lineHeight: 1.5, color: DOCUMENT.body, marginTop: 14 },
  indice: {
    flexDirection: 'row',
    gap: 20,
    paddingBottom: 16,
    marginBottom: 4,
    borderBottomWidth: 0.6,
    borderBottomColor: DOCUMENT.line,
  },
  linkIndice: { fontSize: 9, textDecoration: 'none', color: CST.navy },
  resumo: { fontSize: 11, lineHeight: 1.55, color: DOCUMENT.body, marginTop: 14 },
  subsecao: { fontSize: 12, fontWeight: 600, marginTop: 20, marginBottom: 7 },
  texto: { color: DOCUMENT.body, fontSize: 10.5, lineHeight: 1.5 },
  secaoTitulo: {
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 1.2,
    letterSpacing: -0.3,
    marginTop: 18,
    marginBottom: 16,
  },
  escopo: {
    paddingVertical: 13,
    borderTopWidth: 0.6,
    borderTopColor: DOCUMENT.line,
  },
  escopoTitulo: { fontSize: 12, fontWeight: 600, lineHeight: 1.6, color: CST.navy },
  entregavel: { flexDirection: 'row', gap: 10, marginBottom: 8 },
  check: { marginTop: 2, flexShrink: 0 },
  itemTexto: { flexGrow: 1, flexBasis: 0, fontSize: 10.5, color: DOCUMENT.body },
  marco: {
    flexDirection: 'row',
    gap: 16,
    padding: 14,
    marginBottom: 8,
    backgroundColor: DOCUMENT.soft,
    borderWidth: 0.6,
    borderColor: DOCUMENT.line,
    borderRadius: 10,
  },
  marcoNumero: {
    fontFamily: 'GeistMonoPdf',
    fontWeight: 500,
    fontSize: 10,
    width: 22,
    flexShrink: 0,
    marginTop: 1,
  },
  marcoCorpo: { flexGrow: 1, flexBasis: 0 },
  marcoTitulo: { fontSize: 12, fontWeight: 600, lineHeight: 1.3 },
  marcoDuracao: { fontSize: 9, color: DOCUMENT.faint, marginTop: 3, marginBottom: 7 },
  passo: { flexDirection: 'row', gap: 14, marginBottom: 10 },
  passoNumero: {
    fontFamily: 'GeistMonoPdf',
    fontWeight: 500,
    fontSize: 9,
    width: 22,
    flexShrink: 0,
    marginTop: 1,
  },
  observacoes: { marginTop: 6 },
  assinaturas: { flexDirection: 'row', gap: 30, marginTop: 26 },
  assinatura: { width: '47%' },
  assinaturaLinha: { borderTopWidth: 0.7, borderTopColor: DOCUMENT.signature, marginBottom: 9 },
  assinaturaNome: { fontSize: 10, marginTop: 3 },
  final: { marginTop: 12, paddingTop: 10, borderTopWidth: 0.6, borderTopColor: DOCUMENT.line },
  geradoEm: { fontSize: 8, color: DOCUMENT.faint, marginTop: 8 },
});
