#!/usr/bin/env node
/**
 * vendor-via.mjs — vendors the Viver de IA design system into src/design-system/via/
 *
 * WHY VENDOR INSTEAD OF DEPEND
 * The upstream package is `"private": true` and is not published to npm. A git dependency
 * would force the DS's own toolchain (Vite 8 + TS 6) to run inside every Vercel build, and
 * its `build:lib` output is a single bundle with no per-component "use client" — which would
 * collapse all 46 components into one client boundary and ship the whole DS as JavaScript on
 * a landing page whose traffic is bought. Vendoring the source lets Turbopack treat the DS as
 * first-party code: CSS collected per route, real tree-shaking, exact types, zero build steps.
 *
 * THE POINT OF THIS SCRIPT
 * Injecting `"use client"` PER FILE. Measured on v0.6.1: 36 of 46 components need it, 10 do
 * not. Those 10 (Button, Card, Pill, Input, Icon, Avatar, EmptyState, Progress, Skeleton,
 * Spinner) stay Server Components, which is what lets the entire landing page render with
 * essentially zero design-system JavaScript.
 *
 * IDEMPOTENCE
 * Generated banners use the PINNED COMMIT'S DATE, never `new Date()`, so re-running produces
 * a bit-identical tree. That is what makes `check-ds-drift.mjs` a meaningful CI gate rather
 * than a source of spurious diffs.
 *
 * TO UPGRADE: bump UPSTREAM_COMMIT + UPSTREAM_DATE, run `npm run vendor:via`, review the diff.
 * The diff IS the changelog.
 */
import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  rmSync,
  readdirSync,
  statSync,
  cpSync,
} from 'node:fs';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// ─── Pin ──────────────────────────────────────────────────────────────────────
const UPSTREAM_REPO = 'https://github.com/rafaelmilagre7/viver-de-ia-ds';
// v0.6.1 — fonte canônica que alimenta o site vivo do Design System.
// O SHA continua pinado: a plataforma só muda quando este diff é revisado.
const UPSTREAM_COMMIT = 'ed6fb6b0f0a72bbf62b838fef57e2d34f7e7b066';
const UPSTREAM_DATE = '2026-08-06'; // pinned; never new Date()
const UPSTREAM_VERSION = '0.6.1';

const OUT_DIR = process.env.VIA_OUT_DIR ?? resolve(ROOT, 'src/design-system/via');
const CLONE_DIR =
  process.env.VIA_CLONE_DIR ?? join(tmpdir(), `viver-de-ia-ds-${UPSTREAM_COMMIT.slice(0, 10)}`);

// ─── "use client" classification ──────────────────────────────────────────────
/**
 * A component needs the directive if it uses React state/effects/refs, portals, or
 * touches the DOM. forwardRef alone does NOT require it — it exists in React's
 * react-server build.
 *
 * Deliberately matched on WORD BOUNDARY, not on `hook(`: upstream writes
 * `useState<DateRange>(...)`, and requiring a paren right after the name silently
 * misses every generic call site. Merely importing a hook already means the module
 * belongs to the client graph, so the import line is a sufficient signal.
 *
 * The bias is intentional: a false positive costs one component its RSC optimization;
 * a false negative is a runtime crash in production.
 */
const NEEDS_CLIENT =
  /\buse(State|Effect|LayoutEffect|Ref|Reducer|Callback|Memo|Id|Transition|SyncExternalStore|DeferredValue|ImperativeHandle|DialogFocus)\b|\bcreatePortal\b|\baddEventListener\b|\bdocument\.|\bwindow\./;

/** Escape hatches for heuristic misses. Add with a comment explaining why. */
const FORCE_CLIENT = new Set([]);
const FORCE_SERVER = new Set([]);

/**
 * Vendored third-party source is not ours to typecheck.
 *
 * This project runs `noUncheckedIndexedAccess`, which upstream was not authored
 * against — it produces 23 errors across 9 DS files, all of the `arr[i] is possibly
 * undefined` kind. The choice is between weakening the flag for OUR code or not
 * reporting diagnostics for THEIR code. The second is strictly better: upstream has
 * its own strict CI, and here the DS is additionally guarded by check-ds-drift plus
 * the build itself.
 *
 * `@ts-nocheck` only suppresses diagnostics — inference and declaration emit still
 * work, so consumers keep full types and autocomplete. Verified: a bad `variant`
 * prop at a call site is still a compile error.
 */
const TS_NOCHECK = '// @ts-nocheck — vendored; see PROVENANCE.md\n';

const banner = (what) =>
  `/* ${what}\n` +
  ` * VENDORED — DO NOT EDIT. Generated by scripts/vendor-via.mjs\n` +
  ` * Source: ${UPSTREAM_REPO}\n` +
  ` * Commit: ${UPSTREAM_COMMIT} (v${UPSTREAM_VERSION}, ${UPSTREAM_DATE})\n` +
  ` */\n`;

function log(msg) {
  if (!process.env.VIA_QUIET) console.log(msg);
}

// ─── 1 · Fetch upstream at the pinned commit ──────────────────────────────────
function fetchUpstream() {
  if (existsSync(join(CLONE_DIR, '.git'))) {
    const head = execFileSync('git', ['-C', CLONE_DIR, 'rev-parse', 'HEAD'], {
      encoding: 'utf8',
    }).trim();
    if (head === UPSTREAM_COMMIT) {
      log(`· reusing cached clone at ${CLONE_DIR}`);
      return;
    }
    rmSync(CLONE_DIR, { recursive: true, force: true });
  }
  log(`· cloning ${UPSTREAM_REPO} @ ${UPSTREAM_COMMIT.slice(0, 10)}`);
  mkdirSync(CLONE_DIR, { recursive: true });
  execFileSync('git', ['init', '-q'], { cwd: CLONE_DIR });
  execFileSync('git', ['remote', 'add', 'origin', UPSTREAM_REPO], { cwd: CLONE_DIR });
  execFileSync('git', ['fetch', '-q', '--depth', '1', 'origin', UPSTREAM_COMMIT], {
    cwd: CLONE_DIR,
  });
  execFileSync('git', ['checkout', '-q', 'FETCH_HEAD'], { cwd: CLONE_DIR });
}

// ─── 2 · Discover components ──────────────────────────────────────────────────
function listComponents(srcComponents) {
  return readdirSync(srcComponents)
    .filter((name) => !name.startsWith('_') && !name.startsWith('.'))
    .filter((name) => statSync(join(srcComponents, name)).isDirectory())
    .filter((name) => existsSync(join(srcComponents, name, `${name}.tsx`)))
    .sort();
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

// ─── 3 · Transform + write ────────────────────────────────────────────────────
function classify(name, source) {
  if (FORCE_SERVER.has(name)) return { kind: 'server', reason: 'forced' };
  if (FORCE_CLIENT.has(name)) return { kind: 'client', reason: 'forced' };
  const match = source.match(NEEDS_CLIENT);
  return match
    ? { kind: 'client', reason: match[0].replace(/\s*\($/, '') }
    : { kind: 'server', reason: 'pure' };
}

function main() {
  fetchUpstream();

  const upstreamSrc = join(CLONE_DIR, 'src');
  // Upstream keeps the library primitives in src/lib/ (src/components/ holds the docs
  // site's own components, which we do not want).
  const srcComponents = join(upstreamSrc, 'lib');
  if (!existsSync(srcComponents)) {
    console.error(`✗ Upstream layout changed: ${srcComponents} not found.`);
    process.exit(1);
  }

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const components = listComponents(srcComponents);
  log(`· ${components.length} components found`);

  const manifest = {};
  let clientCount = 0;

  // 3a · components
  for (const name of components) {
    const from = join(srcComponents, name);
    const to = join(OUT_DIR, 'components', name);
    mkdirSync(to, { recursive: true });

    for (const file of walk(from)) {
      const rel = relative(from, file);
      // Tests and stories are upstream's business, not ours.
      if (/\.(test|spec|stories)\.[jt]sx?$/.test(rel)) continue;

      const target = join(to, rel);
      mkdirSync(dirname(target), { recursive: true });

      if (!/\.tsx?$/.test(rel)) {
        cpSync(file, target);
        continue;
      }

      let source = readFileSync(file, 'utf8');
      const isEntry = rel === `${name}.tsx`;
      const { kind, reason } = classify(name, source);

      // Order matters twice over:
      //   · `@ts-nocheck` only applies if it precedes every STATEMENT in the file.
      //   · `'use client'` must be the first statement (a directive prologue).
      // Comments do not break a directive prologue, so the comment goes first and
      // both constraints hold.
      source = TS_NOCHECK + (kind === 'client' ? `'use client';\n\n` : '') + source;
      writeFileSync(target, source);

      if (isEntry) {
        manifest[name] = kind === 'client' ? `client:${reason}` : 'server';
        if (kind === 'client') clientCount++;
      }
    }
  }

  // 3b · shared internals
  const shared = join(srcComponents, '_shared');
  if (existsSync(shared)) {
    for (const file of walk(shared)) {
      const target = join(OUT_DIR, 'components/_shared', relative(shared, file));
      mkdirSync(dirname(target), { recursive: true });
      let source = readFileSync(file, 'utf8');
      if (/\.tsx?$/.test(file)) {
        source = TS_NOCHECK + (NEEDS_CLIENT.test(source) ? `'use client';\n\n` : '') + source;
      }
      writeFileSync(target, source);
    }
  }

  // 3c · styles, tokens, base — copied VERBATIM.
  // No token surgery, no [data-via-screen] scoping: this project has no legacy to leak
  // into, so it gets the reference platform's "wave 6" end state on day one. Dark blocks
  // stay in tokens.css; `data-theme="light"` is pinned on <html>, so enabling dark mode
  // later is an attribute flip rather than a re-vendor.
  // tokens.css is a single file carrying BOTH the custom properties and the signature
  // utility classes (.via-mesh-navy, .via-noise, .via-glass*, .via-hero, .via-label…).
  // It is copied whole — dark blocks included; `data-theme="light"` is pinned on <html>.
  const styleFiles = [
    ['src/styles/tokens.css', 'styles/tokens.css'],
    ['src/styles/form-fields.css', 'styles/form-fields.css'],
    ['src/lib/tokens.ts', 'tokens.ts'],
    ['src/lib/styles.d.ts', 'styles.d.ts'],
  ];
  const copiedStyles = [];
  for (const [from, to] of styleFiles) {
    const abs = join(CLONE_DIR, from);
    if (!existsSync(abs)) continue;
    const target = join(OUT_DIR, to);
    mkdirSync(dirname(target), { recursive: true });
    let source = readFileSync(abs, 'utf8');
    // Upstream defines --via-border-strong twice: once as a color, once as a `1px solid`
    // shorthand. The second wins, silently breaking any color usage. Rename the color.
    if (to === 'styles/tokens.css') {
      source = source.replace(
        /(--via-border-strong)(\s*:\s*(?!1px)[^;]+;)/,
        '--via-border-strong-color$2',
      );
    }
    writeFileSync(target, source);
    copiedStyles.push(to);
  }

  // 3c-bis · base reset, derived from upstream src/index.css.
  // Three things are stripped, all because Next owns them:
  //   - the Google Fonts @import (we self-host Geist via next/font/local)
  //   - the @import of the style files (globals.css imports them explicitly, in order)
  //   - the #root rules (Next has no #root element)
  const indexCss = join(CLONE_DIR, 'src/index.css');
  if (existsSync(indexCss)) {
    const base = readFileSync(indexCss, 'utf8')
      .split('\n')
      .filter((line) => !/^\s*@import\s/.test(line))
      .join('\n')
      .replace(/^#root\s*\{[^}]*\}\s*$/gm, '')
      .replace(/,\s*#root\b/g, '')
      .replace(/\n{3,}/g, '\n\n');
    const target = join(OUT_DIR, 'base/via-base.css');
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, base);
    copiedStyles.push('base/via-base.css');
  }

  // 3d · barrel
  const exports = components
    .map((name) => `export * from './components/${name}/${name}';`)
    .join('\n');
  writeFileSync(
    join(OUT_DIR, 'index.ts'),
    `${banner('DS VIA · barrel')}\n` +
      `/* Theming is intentionally NOT exported. ThemeProvider/applyTheme/useTheme set\n` +
      ` * data-theme on <html>, which is incompatible with this project's light-only pin. */\n\n` +
      `${exports}\n` +
      (existsSync(join(OUT_DIR, 'tokens.ts')) ? `\nexport * from './tokens';\n` : ''),
  );

  // 3e · package.json marker so bundlers keep the CSS side effects
  writeFileSync(
    join(OUT_DIR, 'package.json'),
    JSON.stringify(
      { name: 'design-system-via-vendored', private: true, sideEffects: ['**/*.css'] },
      null,
      2,
    ) + '\n',
  );

  // 3f · client/server manifest — committed, so classification changes show up in review
  writeFileSync(join(OUT_DIR, 'DS_CLIENT.json'), JSON.stringify(manifest, null, 2) + '\n');

  // 3g · provenance
  const serverList = Object.entries(manifest)
    .filter(([, v]) => v === 'server')
    .map(([k]) => k);
  writeFileSync(
    join(OUT_DIR, 'PROVENANCE.md'),
    `# DS VIA — Provenance\n\n` +
      `**DO NOT EDIT ANYTHING IN THIS DIRECTORY.** It is generated by \`scripts/vendor-via.mjs\`\n` +
      `and verified in CI by \`scripts/check-ds-drift.mjs\`.\n\n` +
      `| | |\n|---|---|\n` +
      `| Source | ${UPSTREAM_REPO} |\n` +
      `| Commit | \`${UPSTREAM_COMMIT}\` |\n` +
      `| Version | v${UPSTREAM_VERSION} |\n` +
      `| Pinned date | ${UPSTREAM_DATE} |\n` +
      `| Components | ${components.length} (${clientCount} client, ${serverList.length} server) |\n\n` +
      `## Transforms applied\n\n` +
      `1. **\`'use client'\` injected per file** where the source uses React state/effects/refs,\n` +
      `   portals, or DOM listeners. Everything else stays a Server Component.\n` +
      `2. **\`--via-border-strong\` de-duplicated** — upstream declares it twice (a color and a\n` +
      `   \`1px solid\` shorthand); the color is renamed to \`--via-border-strong-color\`.\n\n` +
      `Deliberately NOT applied: no \`[data-via-screen]\` scoping, no \`ViaScreen\` wrapper, no\n` +
      `token-file surgery, no dark-block stripping. This project has no legacy styles to leak\n` +
      `into, so base styles are global and \`data-theme="light"\` is pinned on \`<html>\`.\n\n` +
      `## Server Components (zero JS)\n\n` +
      serverList.map((n) => `- ${n}`).join('\n') +
      `\n\n## Styles\n\n` +
      copiedStyles.map((s) => `- \`${s}\``).join('\n') +
      `\n`,
  );

  log(`✓ vendored ${components.length} components → ${relative(ROOT, OUT_DIR)}`);
  log(`  ${serverList.length} server · ${clientCount} client`);
  log(`  server: ${serverList.join(', ')}`);
}

main();
