-- =============================================================================
-- CATÁLOGO DOS CINCO PROJETOS
--
-- Reposiciona os cinco registros existentes sem trocar UUIDs: propostas e
-- entregas já criadas preservam sua origem e seu snapshot. Slug, conteúdo e
-- progresso editorial mudam porque agora são projetos diferentes.
-- =============================================================================

begin;

update public.solucoes
set
  slug = case slug
    when 'atendimento-com-ia-no-whatsapp' then 'sdr-atendimento-qualificacao'
    when 'qualificacao-de-leads-com-ia' then 'maquina-prospeccao-b2b'
    when 'crm-comercial-com-ia' then 'inteligencia-comercial-com-ia'
    when 'maquina-de-conteudo-com-ia' then 'operacao-conteudo-multicanal'
    when 'financeiro-sem-planilhas' then 'radar-satisfacao-com-ia'
  end,
  titulo = case slug
    when 'atendimento-com-ia-no-whatsapp' then 'SDR de Atendimento e Qualificação'
    when 'qualificacao-de-leads-com-ia' then 'Máquina de Prospecção B2B'
    when 'crm-comercial-com-ia' then 'Inteligência Comercial com IA'
    when 'maquina-de-conteudo-com-ia' then 'Operação de Conteúdo Multicanal'
    when 'financeiro-sem-planilhas' then 'Radar de Satisfação com IA'
  end,
  resumo = case slug
    when 'atendimento-com-ia-no-whatsapp' then 'Implemente um SDR no WhatsApp que atende, qualifica, agenda e transfere cada conversa para uma pessoa sem perder o contexto.'
    when 'qualificacao-de-leads-com-ia' then 'Construa uma operação que encontra empresas, identifica decisores, enriquece dados e entrega uma lista B2B priorizada ao comercial.'
    when 'crm-comercial-com-ia' then 'Transforme reuniões em transcrição, fatos, tarefas, atualização do CRM e follow-up pronto para o vendedor revisar.'
    when 'maquina-de-conteudo-com-ia' then 'Monte uma operação que transforma conhecimento da empresa em pautas, conteúdos adaptados por canal e calendário com aprovação humana.'
    when 'financeiro-sem-planilhas' then 'Implemente pesquisas de satisfação, análise dos comentários e alertas para recuperar clientes insatisfeitos antes que eles se percam.'
  end,
  categoria = case slug
    when 'atendimento-com-ia-no-whatsapp' then 'Atendimento e vendas'
    when 'qualificacao-de-leads-com-ia' then 'Prospecção'
    when 'crm-comercial-com-ia' then 'Vendas'
    when 'maquina-de-conteudo-com-ia' then 'Marketing'
    when 'financeiro-sem-planilhas' then 'Experiência do cliente'
  end,
  ordem = case slug
    when 'atendimento-com-ia-no-whatsapp' then 1
    when 'qualificacao-de-leads-com-ia' then 2
    when 'crm-comercial-com-ia' then 3
    when 'maquina-de-conteudo-com-ia' then 4
    when 'financeiro-sem-planilhas' then 5
  end,
  -- O vídeo antigo do primeiro registro ainda ensina atendimento oficial.
  -- Os outros quatro eram de produtos diferentes e não podem aparecer como aula.
  video_url = case
    when slug = 'atendimento-com-ia-no-whatsapp' then video_url
    else null
  end,
  status = 'publicado',
  publicado_em = coalesce(publicado_em, now())
where slug in (
  'atendimento-com-ia-no-whatsapp',
  'qualificacao-de-leads-com-ia',
  'crm-comercial-com-ia',
  'maquina-de-conteudo-com-ia',
  'financeiro-sem-planilhas'
);

delete from public.solucao_itens as item
using public.solucoes as projeto
where item.solucao_id = projeto.id
  and projeto.slug in (
    'sdr-atendimento-qualificacao',
    'maquina-prospeccao-b2b',
    'inteligencia-comercial-com-ia',
    'operacao-conteudo-multicanal',
    'radar-satisfacao-com-ia'
  );

insert into public.solucao_itens (solucao_id, tipo, ordem, titulo, conteudo)
select projeto.id, item.tipo, item.ordem, item.titulo, item.conteudo
from public.solucoes as projeto
join (values
  ('sdr-atendimento-qualificacao', 'etapa', 1, 'Entender atendimento e venda', 'Meça a demanda, desenhe a jornada e transforme o perfil ideal em perguntas verificáveis.'),
  ('sdr-atendimento-qualificacao', 'etapa', 2, 'Preparar canal e contexto', 'Organize WhatsApp oficial, base aprovada, CRM, agenda e regras de passagem humana.'),
  ('sdr-atendimento-qualificacao', 'etapa', 3, 'Construir o SDR', 'Registre a conversa, responda com fontes, qualifique, agende e transfira com contexto.'),
  ('sdr-atendimento-qualificacao', 'etapa', 4, 'Validar os caminhos', 'Teste dúvidas, critérios comerciais, riscos, integrações e a rotina da equipe.'),
  ('sdr-atendimento-qualificacao', 'etapa', 5, 'Entregar a operação', 'Ative um piloto controlado e entregue responsáveis, indicadores e rotina de revisão.'),
  ('sdr-atendimento-qualificacao', 'ferramenta', 1, 'WhatsApp Business Platform', 'Canal oficial para receber mensagens e acompanhar estados de entrega.'),
  ('sdr-atendimento-qualificacao', 'ferramenta', 2, 'Supabase', 'Banco protegido de contatos, conversas, critérios, filas e eventos.'),
  ('sdr-atendimento-qualificacao', 'ferramenta', 3, 'OpenAI API', 'Classificação, resposta contextual, qualificação e resumo da passagem.'),
  ('sdr-atendimento-qualificacao', 'ferramenta', 4, 'Google Calendar', 'Consulta de disponibilidade e agendamento confirmado com o time.'),
  ('sdr-atendimento-qualificacao', 'prompt', 1, 'SDR de atendimento', 'Atenda usando somente as fontes aprovadas. Faça uma pergunta por vez, separe fato de hipótese e nunca invente política, preço, prazo, disponibilidade ou ação realizada. Transfira quando faltar fonte, houver risco, o cliente pedir uma pessoa ou a confiança for baixa.'),
  ('sdr-atendimento-qualificacao', 'prompt', 2, 'Qualificador comercial', 'Compare somente respostas confirmadas com os critérios do perfil ideal. Retorne critério, evidência, lacuna e próxima pergunta. Não presuma orçamento, autoridade, necessidade ou urgência. Explique por que o contato está pronto, ainda precisa de informação ou não deve avançar agora.'),
  ('sdr-atendimento-qualificacao', 'prompt', 3, 'Passagem para o vendedor', 'Resuma objetivo declarado, dados confirmados, critérios atendidos, dúvidas abertas, compromissos e próxima ação. Não atribua emoção, intenção ou urgência que o lead não declarou.'),

  ('maquina-prospeccao-b2b', 'etapa', 1, 'Definir quem procurar', 'Traduza o ICP em filtros, sinais e critérios que uma fonte pública consegue confirmar.'),
  ('maquina-prospeccao-b2b', 'etapa', 2, 'Preparar fontes e dados', 'Escolha provedores, campos, deduplicação, CRM e limites de uso dos dados.'),
  ('maquina-prospeccao-b2b', 'etapa', 3, 'Construir a prospecção', 'Encontre empresas, identifique decisores, enriqueça e priorize com evidências.'),
  ('maquina-prospeccao-b2b', 'etapa', 4, 'Validar a qualidade', 'Audite uma amostra, meça cobertura e corrija falsos positivos antes de escalar.'),
  ('maquina-prospeccao-b2b', 'etapa', 5, 'Entregar a rotina', 'Entregue o primeiro lote e um processo repetível, aprovado e conectado ao CRM.'),
  ('maquina-prospeccao-b2b', 'ferramenta', 1, 'Apollo', 'Busca de empresas, pessoas e dados profissionais conforme os filtros definidos.'),
  ('maquina-prospeccao-b2b', 'ferramenta', 2, 'Firecrawl', 'Leitura das páginas públicas da empresa e coleta de sinais verificáveis.'),
  ('maquina-prospeccao-b2b', 'ferramenta', 3, 'Supabase', 'Cadastro único, fontes, status de validação e exportação para o CRM.'),
  ('maquina-prospeccao-b2b', 'ferramenta', 4, 'OpenAI API', 'Classificação dos sinais e produção do briefing sem inventar fatos.'),
  ('maquina-prospeccao-b2b', 'prompt', 1, 'Analista de contas B2B', 'Avalie a empresa apenas com os dados e fontes recebidos. Para cada critério do ICP, retorne confirmado, não confirmado ou desconhecido, junto da evidência e URL. Ausência de evidência nunca significa que o critério foi atendido.'),
  ('maquina-prospeccao-b2b', 'prompt', 2, 'Priorizador de contas', 'Ordene as contas pelos critérios e pesos fornecidos. Mostre a conta do score, diferencie perfil de sinal de compra e não crie urgência. Empates permanecem empates até aparecer um novo fato.'),
  ('maquina-prospeccao-b2b', 'prompt', 3, 'Briefing de prospecção', 'Prepare um briefing curto com atividade da empresa, decisor identificado, sinais recentes, hipótese explicitamente rotulada, fonte e pergunta de abertura. Não escreva uma mensagem de envio automático e não use dado sensível.'),

  ('inteligencia-comercial-com-ia', 'etapa', 1, 'Entender como a venda acontece', 'Mapeie a reunião, o playbook, as objeções e os fatos que precisam alimentar o CRM.'),
  ('inteligencia-comercial-com-ia', 'etapa', 2, 'Preparar captura e integrações', 'Organize consentimento, áudio, transcrição, participantes, CRM e responsáveis.'),
  ('inteligencia-comercial-com-ia', 'etapa', 3, 'Construir a inteligência', 'Transforme a call em fatos, tarefas, coaching, follow-up e contexto da proposta.'),
  ('inteligencia-comercial-com-ia', 'etapa', 4, 'Validar com reuniões reais', 'Compare a leitura da IA com vendedores e teste o caminho completo até o CRM.'),
  ('inteligencia-comercial-com-ia', 'etapa', 5, 'Entregar a rotina comercial', 'Ative com um grupo piloto e institua a revisão semanal de qualidade e resultado.'),
  ('inteligencia-comercial-com-ia', 'ferramenta', 1, 'Plataforma de calls', 'Sala, participantes, gravação e eventos confiáveis da reunião.'),
  ('inteligencia-comercial-com-ia', 'ferramenta', 2, 'OpenAI Transcription', 'Transcrição com marcação temporal para sustentar cada insight.'),
  ('inteligencia-comercial-com-ia', 'ferramenta', 3, 'OpenAI API', 'Extração de fatos, coaching, tarefas, follow-up e briefing da proposta.'),
  ('inteligencia-comercial-com-ia', 'ferramenta', 4, 'Supabase', 'Histórico da call, vínculo com a oportunidade e atualização factual do CRM.'),
  ('inteligencia-comercial-com-ia', 'prompt', 1, 'Analista da reunião', 'Extraia somente fatos presentes na transcrição. Para cada dor, objeção, compromisso e próxima ação, inclua o trecho e o horário que sustentam a leitura. Separe claramente fala do lead, fala do vendedor e inferência.'),
  ('inteligencia-comercial-com-ia', 'prompt', 2, 'Coach comercial', 'Compare a conversa com o playbook fornecido. Recomende uma ação curta por vez e apenas quando houver evidência no diálogo. Não interrompa por estilo pessoal, não invente objeções e priorize perguntas que esclareçam lacunas reais.'),
  ('inteligencia-comercial-com-ia', 'prompt', 3, 'Follow-up da reunião', 'Escreva um rascunho curto com contexto, decisões, próximos passos, responsáveis e datas declaradas. Não acrescente promessa, prazo, desconto ou compromisso que não aparece na conversa. O vendedor precisa revisar antes do envio.'),

  ('operacao-conteudo-multicanal', 'etapa', 1, 'Definir tese e público', 'Registre posicionamento, público, pilares, provas e assuntos que a marca não aborda.'),
  ('operacao-conteudo-multicanal', 'etapa', 2, 'Preparar a matéria-prima', 'Organize fontes próprias, referências, voz, canais, papéis e aprovação.'),
  ('operacao-conteudo-multicanal', 'etapa', 3, 'Construir a produção', 'Implemente pesquisa, pauta, rascunho, adaptação, revisão e calendário.'),
  ('operacao-conteudo-multicanal', 'etapa', 4, 'Validar voz e qualidade', 'Teste fatos, originalidade, aderência à marca e composição em cada canal.'),
  ('operacao-conteudo-multicanal', 'etapa', 5, 'Entregar trinta dias', 'Entregue biblioteca, calendário, conteúdo aprovado e rotina de análise.'),
  ('operacao-conteudo-multicanal', 'ferramenta', 1, 'Supabase', 'Biblioteca de fontes, pautas, versões, aprovações e calendário.'),
  ('operacao-conteudo-multicanal', 'ferramenta', 2, 'OpenAI API', 'Síntese de fontes, pauta, rascunho e adaptação conforme a voz aprovada.'),
  ('operacao-conteudo-multicanal', 'ferramenta', 3, 'Transcrição de vídeo', 'Transformação de falas próprias em matéria-prima pesquisável.'),
  ('operacao-conteudo-multicanal', 'ferramenta', 4, 'APIs dos canais', 'Publicação apenas depois da aprovação explícita e registro da versão.'),
  ('operacao-conteudo-multicanal', 'prompt', 1, 'Editor de pauta', 'Use as fontes fornecidas para propor pautas específicas. Para cada uma, declare tese, evidência, consequência, formato e público. Rejeite ideias sem prova ou que apenas repitam um assunto genérico.'),
  ('operacao-conteudo-multicanal', 'prompt', 2, 'Redator de origem', 'Escreva a peça principal usando somente as fontes e a voz aprovadas. Preserve opinião, atribua números e não crie case, cliente, estatística ou experiência. Marque explicitamente qualquer lacuna que exija validação humana.'),
  ('operacao-conteudo-multicanal', 'prompt', 3, 'Adaptador multicanal', 'Adapte a mesma tese à linguagem e ao espaço de cada canal sem trocar o argumento, a prova ou o sentido. Não publique, não adicione urgência e devolva cada versão com checklist de revisão.'),

  ('radar-satisfacao-com-ia', 'etapa', 1, 'Definir o que medir', 'Escolha o momento, a pergunta e a ação que cada tipo de resposta deve gerar.'),
  ('radar-satisfacao-com-ia', 'etapa', 2, 'Preparar base e canal', 'Organize contatos, consentimento, identidade da pesquisa e responsáveis pelo retorno.'),
  ('radar-satisfacao-com-ia', 'etapa', 3, 'Construir o radar', 'Envie, colete, classifique comentários e alerte a pessoa certa.'),
  ('radar-satisfacao-com-ia', 'etapa', 4, 'Validar em um piloto', 'Teste respostas, falhas, alertas e recuperação com um grupo pequeno.'),
  ('radar-satisfacao-com-ia', 'etapa', 5, 'Entregar e acompanhar', 'Ative a pesquisa e entregue painel, rotina e primeiro relatório de aprendizados.'),
  ('radar-satisfacao-com-ia', 'ferramenta', 1, 'Formulário próprio', 'Coleta simples de nota, comentário e autorização de contato.'),
  ('radar-satisfacao-com-ia', 'ferramenta', 2, 'Supabase', 'Base da campanha, respostas, alertas e histórico de recuperação.'),
  ('radar-satisfacao-com-ia', 'ferramenta', 3, 'Resend', 'Convites e lembretes por e-mail com controle de entrega e opt-out.'),
  ('radar-satisfacao-com-ia', 'ferramenta', 4, 'OpenAI API', 'Classificação de temas, resumo e sugestão de resposta para revisão humana.'),
  ('radar-satisfacao-com-ia', 'prompt', 1, 'Analista de feedback', 'Classifique o comentário por tema, urgência e sentimento usando apenas as palavras do cliente. Cite o trecho que sustenta a classificação. Não diagnostique intenção, não minimize críticas e marque como desconhecido o que não estiver explícito.'),
  ('radar-satisfacao-com-ia', 'prompt', 2, 'Resumo da campanha', 'Agrupe respostas por tema, conte ocorrências e mostre exemplos curtos anonimizados. Separe dado, hipótese e recomendação. Não generalize a base inteira a partir de poucas respostas.'),
  ('radar-satisfacao-com-ia', 'prompt', 3, 'Rascunho de recuperação', 'Prepare uma resposta humana que reconheça o problema declarado, peça o contexto que falta e proponha o próximo contato. Não prometa compensação, prazo ou solução sem aprovação do responsável.')
) as item(slug, tipo, ordem, titulo, conteudo)
  on projeto.slug = item.slug;

update public.projeto_roteiros as roteiro
set
  resultado = 'Um SDR disponível no WhatsApp que atende, qualifica, agenda e transfere a oportunidade com todo o contexto para uma pessoa.',
  cliente_ideal = 'Empresas que recebem leads pelo WhatsApp, demoram para responder, repetem as mesmas perguntas ou usam o tempo dos vendedores para descobrir se o contato tem perfil.',
  entregavel_final = 'Canal oficial, base aprovada, critérios de qualificação, agenda, CRM, passagem humana, testes, indicadores e manual de operação.',
  roteiro = $sdr${
    "fundamentos": [
      {"titulo":"Uma conversa, um dono","descricao":"IA e atendente nunca disputam a mesma conversa. Toda passagem muda o estado e define uma pessoa responsável."},
      {"titulo":"Fato antes de score","descricao":"A qualificação usa respostas confirmadas. Dado ausente permanece como lacuna e nunca vira pontuação positiva."},
      {"titulo":"Fonte ou transferência","descricao":"O SDR responde somente com conhecimento aprovado. Sem fonte suficiente, pergunta ou transfere em vez de improvisar."}
    ],
    "fases": [
      {"id":"entender","titulo":"Entender","objetivo":"Transformar atendimento e qualificação atuais em um mapa verificável antes de automatizar.","passos":[
        {"id":"mapear-jornada","titulo":"Mapear a conversa até a reunião","acao":"Acompanhe uma semana de conversas e desenhe desde a primeira mensagem até resposta, qualificação, agenda, transferência ou encerramento.","concluidoQuando":"O mapa mostra origens, horários, assuntos, tempos, decisões, responsáveis e desfechos de uma semana real.","entregavel":"Mapa da jornada do lead.","duracao":"60–90 min","insumos":["Conversas reais de sete dias","Agenda e etapas comerciais atuais","Uma pessoa do atendimento e uma de vendas"],"execucao":["Exporte as conversas e retire dados pessoais desnecessários da amostra de trabalho.","Marque origem, horário, primeiro retorno, perguntas repetidas, abandono, agendamento e transferência.","Desenhe o caminho principal e as exceções que hoje dependem da memória da equipe.","Valide o mapa com atendimento e vendas e registre divergências antes de decidir o fluxo novo."],"atencao":"Não desenhe a jornada a partir do processo oficial sem confrontá-lo com conversas reais; o fluxo praticado costuma ser diferente.","modelo":{"titulo":"Mapa da jornada do lead","conteudo":"Etapa | Gatilho de entrada | Pergunta ou ação | Informação necessária | Responsável | Prazo | Próximo estado | Evidência\nEntrada | nova mensagem | identificar motivo | nome e origem | atendimento | 5 min | triagem | evento registrado"}},
        {"id":"definir-qualificacao-limites","titulo":"Definir qualificação e limites","acao":"Converta o perfil ideal em critérios confirmáveis e liste tudo que exige uma pessoa, incluindo negociação, reclamação, dado sensível e pedido explícito.","concluidoQuando":"Cada critério tem pergunta, evidência e efeito; cada limite tem gatilho, destino humano e prazo.","entregavel":"Matriz de qualificação e passagem.","duracao":"60–90 min","insumos":["Perfil ideal aprovado","Critérios usados pelos vendedores","Políticas e temas de risco"],"execucao":["Liste no máximo seis critérios que realmente mudam a decisão comercial.","Para cada critério, escreva a pergunta e o dado objetivo que confirma a resposta.","Defina os estados pronto, precisa de informação e não avançar agora sem usar intuição como regra.","Liste gatilhos de transferência e nomeie fila, responsável e prazo de resposta para cada um."],"atencao":"Não transforme BANT ou outro método em interrogatório. Pergunte apenas o necessário e distribua as perguntas ao longo da conversa.","modelo":{"titulo":"Matriz de decisão do SDR","conteudo":"Critério | Pergunta natural | Evidência aceita | Peso | Se faltar\nPerfil da empresa | Em que tipo de operação será usado? | segmento declarado | 2 | perguntar\n\nGatilho de passagem | Destino | Prazo | Mensagem ao cliente\nPedido por pessoa | fila comercial | 5 min | Vou chamar uma pessoa e manter todo o contexto."}}
      ]},
      {"id":"preparar","titulo":"Preparar","objetivo":"Organizar canal, conhecimento, agenda e dados para construir sem improviso.","passos":[
        {"id":"configurar-canal-base","titulo":"Configurar canal e base aprovada","acao":"Valide a conta do WhatsApp, receba um evento de teste e transforme as dúvidas frequentes em respostas curtas, versionadas e ligadas às fontes.","concluidoQuando":"Uma mensagem entra e recebe resposta de teste; as dez dúvidas principais têm resposta, fonte, dono e revisão.","entregavel":"Canal de teste e base versionada.","duracao":"2–4 h","insumos":["Conta Meta Business do cliente","Número oficial e responsável pelo acesso","FAQ, políticas, serviços e horários"],"execucao":["Confirme propriedade do número, conta, aplicativo, webhook e responsável pela renovação dos acessos.","Receba e registre um evento de mensagem e devolva uma resposta autorizada no ambiente de teste.","Escreva uma ficha curta para cada dúvida frequente com fonte, dono, versão e data de revisão.","Marque toda pergunta sem resposta aprovada como passagem obrigatória para uma pessoa."],"atencao":"Nunca coloque token, segredo ou documento privado em código público ou material entregue ao aluno.","modelo":{"titulo":"Ficha de resposta aprovada","conteudo":"Pergunta canônica:\nVariações reais:\nResposta curta:\nAção permitida:\nQuando transferir:\nFonte:\nResponsável:\nAprovado em:\nRevisar em:\nVersão:"}},
        {"id":"preparar-crm-agenda","titulo":"Preparar CRM, agenda e passagem","acao":"Defina o cadastro único do contato, os estados da conversa, os campos de qualificação e como o horário confirmado vira compromisso comercial.","concluidoQuando":"Um lead de teste percorre cadastro, qualificação, agenda e tarefa humana sem duplicar contato ou compromisso.","entregavel":"Contrato de dados e roteamento.","duracao":"90–150 min","insumos":["CRM ou banco do cliente","Calendários dos responsáveis","Matriz de qualificação e passagem"],"execucao":["Defina a chave de deduplicação, os campos obrigatórios e o histórico que nunca pode ser sobrescrito.","Crie estados claros para IA atendendo, aguardando cliente, aguardando pessoa, agendado e encerrado.","Mapeie especialidade, agenda, duração, intervalo e regra de confirmação para cada tipo de reunião.","Simule contato já existente, horário indisponível e transferência fora do expediente."],"atencao":"Agendar não é apenas criar evento. Confirme fuso, participante, duração, responsável e mensagem de confirmação.","modelo":{"titulo":"Contrato mínimo do lead","conteudo":"contato_id:\ntelefone_normalizado:\norigem:\nconversa_estado:\ncriterios_confirmados: []\nlacunas: []\nscore_explicado:\noportunidade_id:\nresponsavel_humano:\nproxima_acao:\nagendamento_id:\nconsentimento_em:"}}
      ]},
      {"id":"construir","titulo":"Construir","objetivo":"Fazer cada mensagem virar histórico, resposta segura, qualificação e próxima ação.","passos":[
        {"id":"registrar-responder","titulo":"Registrar e responder com segurança","acao":"Valide cada evento, grave uma única vez, localize o contato, recupere fontes aprovadas e escolha entre responder, perguntar ou transferir.","concluidoQuando":"Repetir o evento não duplica mensagem e nenhuma resposta sem fonte suficiente é enviada.","entregavel":"Entrada idempotente e agente de atendimento.","duracao":"3–5 h","insumos":["Webhook de teste","Base aprovada","Estados da conversa","Chave de IA guardada no servidor"],"execucao":["Valide assinatura e formato do evento antes de aceitar conteúdo no endereço público.","Registre o identificador do provedor; se já existir, encerre sem processar novamente.","Recupere apenas respostas aprovadas e exija fonte mínima para permitir uma resposta.","Mude o estado antes de transferir para impedir que a IA continue enquanto a pessoa assume."],"atencao":"Responda rapidamente ao provedor e processe a IA fora do recebimento inicial para evitar reenvio por timeout.","modelo":{"titulo":"Decisão estruturada do agente","conteudo":"{\n  \"intencao\": \"categoria aprovada\",\n  \"confianca\": 0.00,\n  \"risco\": false,\n  \"acao\": \"responder | perguntar | transferir\",\n  \"motivo\": \"fato curto\",\n  \"fontes\": [],\n  \"destino_humano\": null\n}"}},
        {"id":"qualificar-agendar","titulo":"Qualificar, agendar e passar o contexto","acao":"Faça perguntas naturais, registre a evidência de cada critério e, quando houver condição, ofereça horários e entregue o briefing ao vendedor.","concluidoQuando":"O vendedor recebe reunião, respostas confirmadas, lacunas, histórico e motivo da prioridade no mesmo registro.","entregavel":"Fluxo comercial do SDR ativo.","duracao":"3–5 h","insumos":["Matriz de qualificação","Agenda conectada","Contato e conversa persistidos","Destino humano configurado"],"execucao":["Escolha a próxima pergunta pela lacuna que mais muda a decisão e faça apenas uma por mensagem.","Grave resposta literal e critério associado antes de recalcular a prioridade.","Ao atingir o estado pronto, consulte horários reais, confirme a escolha e crie o evento uma única vez.","Crie oportunidade e tarefa humana com resumo factual, critérios, lacunas e compromisso já assumido."],"atencao":"Não esconda por que o lead foi priorizado. Um score sem fatos deixa o vendedor refém da automação.","modelo":{"titulo":"Briefing para o vendedor","conteudo":"Objetivo declarado:\nEmpresa e contexto confirmados:\nCritérios atendidos e evidências:\nLacunas abertas:\nDúvidas ou objeções:\nReunião confirmada:\nCompromisso do lead:\nPróxima ação do vendedor:\nLink da conversa:"}}
      ]},
      {"id":"validar","titulo":"Validar","objetivo":"Provar que atendimento, qualificação e passagem funcionam nos caminhos comuns e críticos.","passos":[
        {"id":"testar-cenarios","titulo":"Rodar vinte cenários completos","acao":"Prepare casos comuns, ambíguos, comerciais, críticos e técnicos com resultado esperado antes de conversar com o SDR pelo canal real.","concluidoQuando":"Todos os casos críticos transferem, nenhum inventa informação e toda reprovação foi corrigida e repetida.","entregavel":"Matriz de testes com evidências.","duracao":"90–150 min","insumos":["Canal completo em teste","Duas pessoas testando papéis diferentes","Critério objetivo por cenário"],"execucao":["Escreva cinco dúvidas, cinco qualificações, cinco limites e cinco falhas antes do teste.","Registre entrada, resposta esperada, fonte, decisão, resultado real e evidência de cada caso.","Inclua evento duplicado, agenda indisponível, atendente offline e pedido explícito por pessoa.","Corrija base, regra ou integração conforme a causa e repita todos os casos críticos e reprovados."],"atencao":"Não mude o critério depois de ver a resposta. Isso transforma teste em justificativa do que já foi construído.","modelo":{"titulo":"Matriz de cenários","conteudo":"ID | Categoria | Entrada | Contexto | Resultado esperado | Fonte | Critério esperado | Deve transferir? | Resultado real | Aprovado? | Evidência | Correção | Reteste"}},
        {"id":"validar-com-equipe","titulo":"Calibrar com vendas e operação","acao":"Compare o SDR com leads históricos e faça a equipe concluir atendimentos, agendamentos e passagens usando seus próprios acessos.","concluidoQuando":"A concordância dos critérios está registrada e a equipe conclui três jornadas sem ajuda do implementador.","entregavel":"Aceite comercial e operacional.","duracao":"60–90 min","insumos":["Vinte leads históricos com desfecho","Atendente e vendedor do piloto","Acessos com permissões reais"],"execucao":["Rode os vinte históricos sem mostrar o desfecho à automação e compare classificação com o resultado conhecido.","Revise falsos positivos e negativos com o líder sem ajustar regra para favorecer um caso isolado.","Faça a equipe assumir uma conversa, reagendar uma reunião e corrigir um critério usando a interface.","Registre aceite, divergências aceitas, pendências, dono e prazo de cada ajuste."],"atencao":"Assistir à demonstração não comprova autonomia. Quem vai operar precisa clicar e concluir a jornada.","modelo":{"titulo":"Termo de calibração e aceite","conteudo":"Amostra histórica:\nConcordâncias:\nFalsos positivos:\nFalsos negativos:\nRegras ajustadas:\n\n[ ] assumir conversa\n[ ] reagendar reunião\n[ ] corrigir critério\n[ ] pausar automação\n\nResponsáveis:\nPendências:\nData do aceite:"}}
      ]},
      {"id":"entregar","titulo":"Entregar","objetivo":"Colocar no ar com um recorte controlado e deixar o cliente capaz de operar e melhorar.","passos":[
        {"id":"piloto-controlado","titulo":"Ativar um piloto controlado","acao":"Escolha uma origem, horário ou equipe pequena, acompanhe as primeiras conversas e mantenha um caminho simples para pausar e voltar ao humano.","concluidoQuando":"O lote termina sem conversa órfã, duplicidade, resposta sem fonte ou agendamento incorreto.","entregavel":"Primeiro lote em produção.","duracao":"1 dia acompanhado","insumos":["Testes e aceite aprovados","Responsável humano disponível","Critérios para pausar, corrigir ou ampliar"],"execucao":["Defina recorte, duração, volume esperado e responsáveis técnico e operacional.","Registre as condições que obrigam pausa imediata e teste o botão ou procedimento de contingência.","Acompanhe ao vivo as primeiras dez conversas, incluindo passagem e agenda.","Compare o lote com os critérios e decida formalmente entre corrigir, repetir ou ampliar."],"atencao":"Não ligue toda a base fora do horário da equipe. O primeiro dia precisa de observação humana explícita.","modelo":{"titulo":"Plano do piloto","conteudo":"Recorte:\nData e horário:\nVolume esperado:\nResponsável técnico:\nResponsável operacional:\nCanal de incidente:\nPausar se:\nCritérios para ampliar:\nDecisão final: corrigir | repetir | ampliar"}},
        {"id":"manual-indicadores","titulo":"Entregar manual e indicadores","acao":"Passe acessos, responsabilidades, rotina, contingência e indicadores para o cliente e marque a primeira revisão da operação.","concluidoQuando":"A equipe consegue revisar a base, assumir a fila, pausar o SDR e ler os indicadores sem o implementador.","entregavel":"Manual de operação e agenda de revisão.","duracao":"60–90 min","insumos":["Aprendizados do piloto","Lista final de acessos e responsáveis","Histórico de versões da base","Agenda do responsável"],"execucao":["Documente em linguagem simples como a conversa entra, decide, agenda, transfere e encerra.","Entregue indicadores de volume, primeira resposta, qualificação, agenda, transferência, falha e assunto sem base.","Peça à equipe para revisar uma resposta, trocar um responsável e pausar o SDR usando apenas o manual.","Marque data, participantes e pauta da primeira revisão e registre pendências com dono e prazo."],"atencao":"Código e login não são a entrega. O ativo é uma operação compreensível, mensurável e mantida por responsáveis reais.","modelo":{"titulo":"Índice do manual de operação","conteudo":"1. Escopo e resultado\n2. Canais e responsáveis\n3. Estados da conversa\n4. Base e revisão\n5. Qualificação e score\n6. Agenda e confirmação\n7. Passagem humana\n8. Contingência\n9. Indicadores\n10. Acessos e propriedade\n11. Pendências\n12. Próxima revisão"}}
      ]}
    ]
  }$sdr$::jsonb,
  versao = roteiro.versao + 1
from public.solucoes as projeto
where roteiro.projeto_id = projeto.id
  and projeto.slug = 'sdr-atendimento-qualificacao';

update public.projeto_roteiros as roteiro
set
  resultado = 'Uma máquina que encontra empresas aderentes, identifica decisores, enriquece os dados e entrega contas priorizadas com fontes para o comercial.',
  cliente_ideal = 'Empresas B2B que dependem de listas compradas, pesquisa manual ou indicações e não conseguem explicar por que uma conta deveria ser abordada agora.',
  entregavel_final = 'ICP operacional, fontes configuradas, cadastro deduplicado, enriquecimento, score explicado, primeiro lote validado e rotina de entrega ao CRM.',
  roteiro = $prospeccao${
    "fundamentos": [
      {"titulo":"Fonte em cada fato","descricao":"Todo dado enriquecido preserva origem e horário. Informação sem fonte fica como desconhecida e não influencia a prioridade."},
      {"titulo":"Perfil não é intenção","descricao":"Aderência ao ICP e sinal de compra são medidas diferentes. Uma empresa adequada pode não estar pronta para abordagem."},
      {"titulo":"Aprovação antes do contato","descricao":"A máquina prepara contas e contexto. Envio, canal e mensagem continuam sob decisão humana e respeitam opt-out."}
    ],
    "fases": [
      {"id":"entender","titulo":"Entender","objetivo":"Definir quem procurar e quais fatos tornam uma conta relevante para o cliente.","passos":[
        {"id":"traduzir-icp","titulo":"Traduzir o ICP em filtros","acao":"Converta a descrição do cliente ideal em filtros pesquisáveis, critérios confirmáveis, exclusões e pesos que qualquer pessoa consiga aplicar.","concluidoQuando":"O ICP tem até oito critérios, fontes possíveis, pesos e exemplos claros de conta aderente e não aderente.","entregavel":"Matriz operacional do ICP.","duracao":"60–90 min","insumos":["Clientes ganhos e perdidos","Tese atual de ICP","Uma pessoa de vendas"],"execucao":["Escolha dez clientes bons e dez contas que não deveriam ter avançado.","Compare segmento, porte, localização, tecnologia, modelo e problema até encontrar padrões verificáveis.","Defina critérios obrigatórios, desejáveis e de exclusão sem usar adjetivos vagos.","Aplique a matriz às vinte contas históricas e ajuste os critérios que não separam os grupos."],"atencao":"Evite critérios como empresa inovadora ou em crescimento sem definir qual dado público comprova isso.","modelo":{"titulo":"Matriz do ICP","conteudo":"Critério | Tipo: obrigatório, desejável ou exclusão | Filtro | Fonte | Peso | Exemplo positivo | Exemplo negativo\nSegmento | obrigatório | CNAE ou descrição | site e Receita | 3 | ... | ..."}},
        {"id":"definir-sinais-limites","titulo":"Definir sinais e limites de uso","acao":"Liste eventos públicos que aumentam prioridade e documente quais dados, fontes, canais e práticas não serão usados.","concluidoQuando":"Cada sinal tem janela, fonte e efeito; cada exclusão de privacidade ou abordagem está registrada e aprovada.","entregavel":"Mapa de sinais e governança.","duracao":"45–60 min","insumos":["Ciclo de compra conhecido","Política comercial e de privacidade","Canais autorizados"],"execucao":["Liste fatos recentes ligados ao problema, como contratação, expansão, nova unidade ou mudança de tecnologia.","Defina por quantos dias cada sinal permanece relevante e qual fonte pode confirmá-lo.","Separe dados profissionais necessários de dados pessoais ou sensíveis que não devem entrar.","Registre canal permitido, revisão humana, limite de frequência e condições de opt-out antes de qualquer contato."],"atencao":"Notícia recente não prova intenção de compra. Ela apenas muda a ordem da pesquisa e a hipótese que será validada.","modelo":{"titulo":"Mapa de sinais e limites","conteudo":"Sinal | Fonte | Janela | Peso | Hipótese permitida | Pergunta para validar\n\nNão coletar:\nNão usar como score:\nCanais autorizados:\nAprovação necessária:\nRegra de opt-out:"}}
      ]},
      {"id":"preparar","titulo":"Preparar","objetivo":"Escolher fontes, modelar o cadastro e preparar a passagem ao CRM.","passos":[
        {"id":"modelar-conta","titulo":"Criar o cadastro único","acao":"Defina empresa, pessoa, fonte, sinal, score e status como entidades separadas, com chaves que impedem duplicidade.","concluidoQuando":"Importar a mesma empresa e pessoa por duas fontes não duplica registros e preserva as duas evidências.","entregavel":"Modelo de dados da prospecção.","duracao":"60–120 min","insumos":["Campos exigidos pelo CRM","Exemplos de respostas dos provedores","Matriz do ICP"],"execucao":["Use CNPJ quando disponível e domínio normalizado como chave auxiliar da empresa.","Separe pessoa de empresa e relacione cargo, fonte e data de verificação sem sobrescrever histórico.","Modele critérios e sinais como ocorrências com fonte, valor e horário.","Prepare os estados encontrado, enriquecendo, revisar, aprovado, descartado e enviado ao CRM."],"atencao":"Telefone ou e-mail sozinho não identifica uma empresa. Fusões, filiais e domínios diferentes precisam de revisão explícita.","modelo":{"titulo":"Contrato de dados da conta","conteudo":"empresa_id:\ncnpj:\ndominio_normalizado:\nrazao_social:\nsegmento:\nporte:\nfontes: []\ncriterios: []\nsinais: []\ndecisores: []\nscore_perfil:\nscore_momento:\nstatus_revisao:\natualizado_em:"}},
        {"id":"configurar-fontes-crm","titulo":"Configurar fontes e destino","acao":"Conecte uma fonte empresarial, uma fonte de pessoas e a leitura do site; depois mapeie somente os campos aprovados para o CRM.","concluidoQuando":"Uma conta de teste passa pelas três fontes e chega ao ambiente de teste do CRM com origem e data de cada dado.","entregavel":"Pipeline de fontes conectado.","duracao":"2–4 h","insumos":["Contas dos provedores","Acesso de teste do CRM","Campos e limites aprovados"],"execucao":["Teste cada provedor isoladamente com uma empresa conhecida e guarde resposta, custo e limite.","Normalize os retornos para o contrato de dados antes de combinar as fontes.","Defina precedência por campo sem apagar divergências; dado conflitante precisa de revisão.","Envie uma conta de teste ao CRM e confirme vínculo, fonte, proprietário e status inicial."],"atencao":"Não dependa de um único provedor para todos os campos. Também não combine fontes sem saber qual venceu quando houver conflito.","modelo":{"titulo":"Matriz de fontes","conteudo":"Campo | Fonte principal | Fonte alternativa | Validade | Custo | Se divergir\nEmpresa | ...\nDecisor | ...\nTelefone | ...\nE-mail | ...\nSinal | ..."}}
      ]},
      {"id":"construir","titulo":"Construir","objetivo":"Encontrar, enriquecer e priorizar contas de forma rastreável.","passos":[
        {"id":"buscar-enriquecer","titulo":"Buscar e enriquecer contas","acao":"Transforme filtros em buscas controladas, deduplique as empresas e colete apenas os dados necessários para confirmar ICP e decisor.","concluidoQuando":"O lote bruto não tem duplicidades conhecidas e cada campo utilizado mostra fonte e horário.","entregavel":"Lote enriquecido e rastreável.","duracao":"3–5 h","insumos":["ICP operacional","Fontes conectadas","Contrato de dados"],"execucao":["Execute uma busca pequena por filtro e registre consulta, página e custo antes de paginar.","Normalize empresa e domínio, una duplicatas e preserve as fontes que apontaram para o registro.","Leia páginas públicas relevantes e extraia somente trechos ligados aos critérios e sinais aprovados.","Procure pessoas apenas nas funções definidas; dados ausentes seguem vazios e entram na fila de revisão."],"atencao":"Não aumente o lote para esconder baixa cobertura. Primeiro meça onde cada fonte falha e se o dado faltante realmente muda a decisão.","modelo":{"titulo":"Log do enriquecimento","conteudo":"Lote:\nConsulta:\nFonte:\nIniciado em:\nEmpresas encontradas:\nDuplicatas unidas:\nContas com domínio:\nContas com decisor:\nCampos desconhecidos:\nCusto:\nErros e repetição:"}},
        {"id":"pontuar-briefar","titulo":"Priorizar e gerar o briefing","acao":"Calcule perfil e momento separadamente, explique o resultado com evidências e produza um briefing curto para revisão comercial.","concluidoQuando":"Toda conta priorizada tem score reproduzível, evidências, lacunas e uma hipótese rotulada para a conversa.","entregavel":"Fila priorizada com briefing.","duracao":"2–4 h","insumos":["Lote enriquecido","Pesos do ICP e sinais","Campos de destino do CRM"],"execucao":["Calcule o score de perfil apenas com critérios confirmados e registre a conta por item.","Calcule o score de momento em coluna separada usando somente sinais dentro da janela.","Gere o briefing com fatos, URLs, hipótese e pergunta de validação sem escrever uma falsa personalização.","Envie ao CRM somente contas aprovadas por uma pessoa e preserve as descartadas com motivo."],"atencao":"Não transforme desconhecido em zero se isso penaliza a conta. Desconhecido pede pesquisa ou pergunta; negativo exige evidência.","modelo":{"titulo":"Briefing da conta","conteudo":"Empresa:\nPor que se encaixa no ICP:\nCritérios confirmados e fontes:\nSinais recentes e datas:\nDecisor e fonte:\nLacunas:\nHipótese, não fato:\nPergunta para validar:\nScore de perfil:\nScore de momento:\nRevisado por:"}}
      ]},
      {"id":"validar","titulo":"Validar","objetivo":"Medir precisão, cobertura e custo antes de produzir volume.","passos":[
        {"id":"auditar-amostra","titulo":"Auditar trinta contas","acao":"Selecione uma amostra variada e confira manualmente empresa, decisor, critérios, sinais, score e fontes sem olhar apenas as primeiras posições.","concluidoQuando":"Precisão e cobertura estão calculadas por campo e todos os erros relevantes têm causa e correção.","entregavel":"Relatório de qualidade do lote.","duracao":"90–150 min","insumos":["Trinta contas do lote","Acesso às fontes originais","Pessoa comercial para revisar aderência"],"execucao":["Sorteie contas entre alta, média e baixa prioridade em vez de revisar só as melhores.","Verifique cada campo usado no score diretamente na fonte e classifique correto, incorreto, desatualizado ou ausente.","Calcule precisão, cobertura e custo por conta validada e por decisor encontrado.","Corrija normalização, fonte ou regra e repita a amostra afetada antes de ampliar."],"atencao":"Uma lista pode parecer boa porque nomes e sites estão corretos, enquanto cargo, sinal ou contato que orientam a venda estão errados.","modelo":{"titulo":"Auditoria da amostra","conteudo":"Conta | Campo | Valor coletado | Fonte | Verificação manual | Estado | Impacta score? | Causa | Correção | Reteste\n\nPrecisão por campo:\nCobertura por campo:\nCusto por conta válida:"}},
        {"id":"testar-falhas","titulo":"Testar falhas e repetição","acao":"Simule limite de API, fonte indisponível, site bloqueado, dado conflitante e repetição do mesmo lote sem criar registros ou custos desnecessários.","concluidoQuando":"O processo retoma do ponto correto, não duplica contas e deixa cada falha visível para revisão.","entregavel":"Suíte de resiliência da prospecção.","duracao":"60–90 min","insumos":["Ambiente de teste","Lote já processado","Limites conhecidos dos provedores"],"execucao":["Interrompa cada fonte em um ponto controlado e confirme que o status não aparece como concluído.","Repita o lote e confirme que registros válidos são reutilizados dentro da validade definida.","Introduza dois valores conflitantes e valide que nenhum deles substitui o outro silenciosamente.","Teste exportação repetida ao CRM e bloqueie a criação da mesma conta ou tarefa duas vezes."],"atencao":"Erro silencioso é pior que lote incompleto. A interface precisa dizer o que falhou, qual conta foi afetada e como repetir.","modelo":{"titulo":"Registro de falhas","conteudo":"Cenário | Fonte | Conta afetada | Estado esperado | Estado real | Duplicou? | Cobrou novamente? | Mensagem visível | Retomada | Aprovado?"}}
      ]},
      {"id":"entregar","titulo":"Entregar","objetivo":"Entregar o primeiro lote útil e uma rotina que o cliente consegue repetir.","passos":[
        {"id":"entregar-primeiro-lote","titulo":"Entregar o primeiro lote aprovado","acao":"Revise com vendas um lote pequeno, envie somente as contas aceitas ao CRM e acompanhe o uso para descobrir se o briefing orienta uma boa conversa.","concluidoQuando":"O comercial aceitou ou descartou cada conta com motivo e conseguiu usar os briefings sem pesquisa paralela obrigatória.","entregavel":"Primeiro lote no CRM.","duracao":"1 dia acompanhado","insumos":["Lote auditado","Revisor comercial","CRM de destino"],"execucao":["Escolha entre vinte e cinquenta contas para o primeiro lote e congele a versão dos critérios.","Faça o comercial aceitar, pedir revisão ou descartar cada conta registrando o motivo.","Envie as aprovadas com proprietário, briefing, fontes e próxima ação, sem disparar mensagens automaticamente.","Colete dúvidas e tempo de pesquisa adicional para melhorar a próxima entrega."],"atencao":"Quantidade entregue não é o resultado. O lote vale quando o comercial confia, entende a prioridade e sabe qual pergunta precisa validar.","modelo":{"titulo":"Termo do primeiro lote","conteudo":"Versão do ICP:\nContas revisadas:\nAprovadas:\nDescartadas por motivo:\nCom decisor confirmado:\nTempo de pesquisa adicional:\nDúvidas do comercial:\nAjustes para o próximo lote:\nAceite:"}},
        {"id":"documentar-rotina","titulo":"Documentar a rotina de prospecção","acao":"Entregue consultas, fontes, custos, revisão, exportação, indicadores e contingência para o cliente repetir a produção com controle.","concluidoQuando":"A equipe executa uma busca pequena, revisa uma conta e envia ao CRM usando somente o manual.","entregavel":"Playbook da máquina de prospecção.","duracao":"60–90 min","insumos":["Consultas finais","Matriz de fontes e custos","Aprendizados do lote"],"execucao":["Documente como ajustar filtros sem alterar silenciosamente o ICP aprovado.","Explique validade, custo, limites e contingência de cada fonte.","Defina indicadores de precisão, cobertura, custo por conta válida, aceitação e conversão posterior.","Marque a próxima revisão dos critérios e registre acessos, propriedade, renovação e opt-out."],"atencao":"Não deixe o processo preso ao implementador ou a uma consulta que ninguém entende. Toda mudança precisa ser reproduzível e versionada.","modelo":{"titulo":"Índice do playbook","conteudo":"1. ICP e exclusões\n2. Sinais e janelas\n3. Consultas\n4. Fontes, custos e limites\n5. Deduplicação\n6. Score explicado\n7. Revisão humana\n8. Envio ao CRM\n9. Opt-out e governança\n10. Indicadores\n11. Contingência\n12. Próxima revisão"}}
      ]}
    ]
  }$prospeccao$::jsonb,
  versao = roteiro.versao + 1
from public.solucoes as projeto
where roteiro.projeto_id = projeto.id
  and projeto.slug = 'maquina-prospeccao-b2b';

update public.projeto_roteiros as roteiro
set
  resultado = 'Cada reunião comercial vira transcrição, fatos, coaching, tarefas, CRM atualizado, follow-up e contexto para a proposta.',
  cliente_ideal = 'Times comerciais que fazem reuniões online, registram pouco no CRM e perdem dores, objeções, compromissos e próximos passos em notas dispersas.',
  entregavel_final = 'Captura consentida, transcrição, análise com evidências, Live Coach configurado, tarefas, CRM, follow-up, painel e rotina de qualidade.',
  roteiro = $comercial${
    "fundamentos": [
      {"titulo":"Trecho sustenta insight","descricao":"Dor, objeção, compromisso e recomendação apontam para a fala e o horário que sustentam a leitura."},
      {"titulo":"CRM recebe fatos","descricao":"A automação registra eventos e tarefas confirmadas. Inferências continuam rotuladas e não mudam o funil sozinhas."},
      {"titulo":"Pessoa envia e decide","descricao":"Follow-up, proposta e mudança comercial permanecem sob revisão humana, mesmo quando a IA deixa tudo preparado."}
    ],
    "fases": [
      {"id":"entender","titulo":"Entender","objetivo":"Mapear como a reunião produz decisão e quais informações realmente orientam a venda.","passos":[
        {"id":"mapear-reuniao","titulo":"Mapear a reunião comercial","acao":"Observe reuniões reais e desenhe preparação, abertura, descoberta, apresentação, objeções, compromissos e registro posterior.","concluidoQuando":"O mapa mostra o que deve acontecer, o que acontece de fato e onde contexto ou próxima ação se perdem.","entregavel":"Mapa da jornada da call.","duracao":"60–90 min","insumos":["Três gravações autorizadas","Playbook atual","Vendedor e líder comercial"],"execucao":["Escolha reuniões com desfechos diferentes e confirme autorização de uso da amostra.","Marque cada momento, informação esperada, fala real, decisão e registro feito depois.","Compare o playbook com a prática sem tratar diferença de estilo como erro automático.","Liste as cinco perdas de contexto que mais afetam follow-up, CRM ou proposta."],"atencao":"Não comece pelos indicadores que a ferramenta consegue gerar. Comece pelas decisões que o time precisa tomar depois da reunião.","modelo":{"titulo":"Mapa da call","conteudo":"Momento | Objetivo | Pergunta esperada | Fato a capturar | Ação do vendedor | Evidência na call | Destino no CRM | Lacuna atual"}},
        {"id":"definir-leituras","titulo":"Definir fatos, coaching e indicadores","acao":"Especifique o que a IA extrai, o que pode recomendar ao vivo e quais mudanças dependem de confirmação do vendedor.","concluidoQuando":"Cada saída tem formato, fonte, destino, responsável e regra clara de confirmação.","entregavel":"Contrato da inteligência comercial.","duracao":"60–90 min","insumos":["Mapa da call","Campos e etapas do CRM","Playbook aprovado"],"execucao":["Liste dores, necessidades, objeções, pessoas, decisões, compromissos e tarefas como fatos citáveis.","Defina sugestões do Live Coach que são úteis durante a conversa e limite a uma ação curta por vez.","Separe atualização segura, como criar uma nota, de ação confirmada, como mover etapa ou enviar e-mail.","Escolha indicadores ligados ao processo, como lacunas preenchidas, próximos passos com data e tempo de registro."],"atencao":"Score único esconde erros. Preserve componentes e trechos para o líder discordar de uma leitura específica.","modelo":{"titulo":"Contrato de saída da call","conteudo":"Saída | Tipo: fato, inferência ou recomendação | Evidência obrigatória | Destino | Confirmação humana? | Responsável\nDor | fato | trecho e horário | nota CRM | não | sistema\nMover etapa | ação | critério de passagem | pipeline | sim | vendedor"}}
      ]},
      {"id":"preparar","titulo":"Preparar","objetivo":"Organizar consentimento, captura, identidade da reunião e integrações antes da análise.","passos":[
        {"id":"preparar-captura","titulo":"Preparar sala, áudio e consentimento","acao":"Configure a sala, informe gravação e transcrição, teste fontes de áudio separadas e defina retenção e acesso aos arquivos.","concluidoQuando":"Duas pessoas entram, consentem, falam simultaneamente e a gravação preserva identidade, horário e qualidade suficiente.","entregavel":"Captura de reunião validada.","duracao":"2–4 h","insumos":["Plataforma de calls","Política de privacidade e retenção","Dois participantes de teste"],"execucao":["Defina a mensagem de consentimento e o comportamento quando alguém não aceitar.","Associe cada faixa ao participante pelo identificador da track, não pela ordem de chegada.","Grave entrada, saída, silêncio, reconexão e troca de dispositivo com horários confiáveis.","Proteja gravação e transcrição por dono e estabeleça prazo de retenção e exclusão."],"atencao":"Misturar todas as vozes antes de identificar participantes reduz a utilidade e pode atribuir uma fala à pessoa errada.","modelo":{"titulo":"Checklist de captura","conteudo":"[ ] aviso antes da gravação\n[ ] consentimento registrado\n[ ] participante e track vinculados\n[ ] reconexão testada\n[ ] fala simultânea preservada\n[ ] acesso protegido\n[ ] retenção definida\n[ ] exclusão testada\n[ ] responsável nomeado"}},
        {"id":"conectar-oportunidade","titulo":"Conectar call ao CRM e playbook","acao":"Exija oportunidade e participantes antes de gerar o link e carregue os campos, estágio e playbook corretos para orientar a análise.","concluidoQuando":"A reunião de teste nasce ligada à oportunidade e todos os resultados voltam para a mesma linha do tempo.","entregavel":"Contexto comercial conectado.","duracao":"90–150 min","insumos":["CRM de teste","Playbook versionado","Oportunidade e contatos fictícios"],"execucao":["Defina quem pode gerar o link e quais vínculos são obrigatórios antes da sala existir.","Carregue etapa, histórico, pessoas e objetivo sem enviar ao modelo dados que não ajudam a reunião.","Selecione a versão do playbook pela operação e registre qual versão orientou as recomendações.","Crie uma call de teste e confirme nota, tarefas e fonte_id na oportunidade correta."],"atencao":"Título parecido não é vínculo. Use identificadores do CRM para impedir que duas oportunidades da mesma empresa misturem contexto.","modelo":{"titulo":"Contexto mínimo da call","conteudo":"reuniao_id:\noportunidade_id:\nempresa_id:\nparticipantes: []\nobjetivo:\netapa_atual:\nultimos_fatos: []\nplaybook_id:\nplaybook_versao:\nconsentimento_status:"}}
      ]},
      {"id":"construir","titulo":"Construir","objetivo":"Transformar áudio em orientação útil durante a call e trabalho organizado depois dela.","passos":[
        {"id":"transcrever-coachear","titulo":"Transcrever e orientar em tempo real","acao":"Envie segmentos com identidade e horário, construa a transcrição incremental e mostre recomendações curtas baseadas no playbook e na conversa.","concluidoQuando":"A transcrição acompanha a call e o coach mostra somente sugestões relevantes, com contexto suficiente e atraso aceitável.","entregavel":"Transcrição e Live Coach ativos.","duracao":"4–7 h","insumos":["Captura validada","Playbook versionado","Serviço de transcrição e IA"],"execucao":["Transcreva por participante e guarde início, fim, texto, confiança e origem de cada segmento.","Monte uma janela de contexto que preserve perguntas e respostas sem reenviar a reunião inteira.","Compare lacunas do playbook com o que já foi dito e gere no máximo uma sugestão acionável por vez.","Bloqueie repetição, recomendação baseada em fala antiga e orientação quando a confiança da transcrição estiver baixa."],"atencao":"Coach que fala o tempo todo atrapalha. Silêncio também é uma decisão correta quando não existe recomendação útil.","modelo":{"titulo":"Saída do Live Coach","conteudo":"{\n  \"mostrar\": true,\n  \"tipo\": \"pergunta | alerta | lembrete\",\n  \"texto\": \"uma ação curta\",\n  \"motivo\": \"lacuna ou trecho atual\",\n  \"segmentos\": [\"ids\"],\n  \"expira_em_segundos\": 30\n}"}},
        {"id":"gerar-pos-call","titulo":"Gerar fatos, tarefas e follow-up","acao":"Ao encerrar, consolide a transcrição final, extraia fatos com citações, crie tarefas confirmáveis e prepare follow-up e briefing da proposta.","concluidoQuando":"O vendedor revisa uma tela com fatos, trechos, tarefas e rascunhos e confirma o que entra no CRM ou será enviado.","entregavel":"Revisão pós-call completa.","duracao":"3–5 h","insumos":["Transcrição final","Contrato de saída","Campos do CRM"],"execucao":["Feche segmentos incompletos e marque falhas ou trechos inaudíveis antes da análise.","Extraia fatos, inferências e recomendações em grupos separados, sempre com segmento e horário.","Converta compromissos declarados em tarefas com responsável e data apenas quando aparecerem na conversa.","Apresente atualização do CRM, follow-up e contexto de proposta em revisão única antes de executar qualquer ação."],"atencao":"Não transforme frases como depois conversamos em prazo. Datas e responsáveis ausentes continuam como lacunas para o vendedor completar.","modelo":{"titulo":"Revisão pós-call","conteudo":"Resumo factual:\nDores com trechos:\nObjeções com trechos:\nDecisões:\nCompromissos e datas:\nLacunas:\nTarefas propostas:\nMudança de etapa proposta:\nFollow-up para revisar:\nContexto da proposta:\nFalhas de transcrição:"}}
      ]},
      {"id":"validar","titulo":"Validar","objetivo":"Comparar a IA com a leitura humana e provar o caminho completo até o CRM.","passos":[
        {"id":"comparar-calls","titulo":"Comparar dez reuniões","acao":"Use reuniões com desfechos diferentes e faça vendedor e líder avaliarem fatos, trechos, sugestões, tarefas e rascunhos sem aceitar o resultado automaticamente.","concluidoQuando":"Precisão e utilidade estão medidas por tipo de saída e todas as falhas críticas foram corrigidas e repetidas.","entregavel":"Relatório de calibração comercial.","duracao":"2–3 h","insumos":["Dez reuniões autorizadas","Gabarito humano independente","Critérios de precisão e utilidade"],"execucao":["Crie o gabarito antes de mostrar a análise da IA para reduzir viés de confirmação.","Compare cada dor, objeção, tarefa e recomendação com a transcrição e o gabarito.","Meça precisão por tipo e marque também saída correta mas inútil ou tardia.","Ajuste prompt, contexto ou regra conforme a causa e repita todos os casos críticos."],"atencao":"Média geral pode esconder uma falha grave, como tarefa inventada. Defina tipos que exigem precisão total antes do piloto.","modelo":{"titulo":"Planilha de calibração","conteudo":"Reunião | Tipo de saída | IA | Gabarito | Trecho correto? | Fato correto? | Útil? | No tempo certo? | Gravidade | Causa | Correção | Reteste"}},
        {"id":"testar-ponta-a-ponta","titulo":"Simular o dia comercial","acao":"Agende, realize, desconecte, encerre, revise, confirme e encontre todos os fatos no CRM usando perfis reais da equipe.","concluidoQuando":"Três jornadas terminam sem mistura de oportunidade, perda de transcrição, duplicidade de tarefa ou ação não confirmada.","entregavel":"Aceite ponta a ponta.","duracao":"90–120 min","insumos":["Vendedor, líder e administrador","CRM e sala em teste","Cenários de falha definidos"],"execucao":["Faça uma reunião comum, uma com reconexão e uma encerrada sem fala suficiente.","Revise parcialmente, saia da tela e retome sem perder decisões já confirmadas.","Confirme tarefas e follow-up, recuse mudança de etapa e verifique exatamente o que entrou no CRM.","Valide permissões para gravação, transcrição e análise com cada papel da operação."],"atencao":"Status de processamento concluído não prova entrega. Confirme o conteúdo no CRM e a ação visível para quem trabalha.","modelo":{"titulo":"Roteiro ponta a ponta","conteudo":"Cenário | Link ligado à oportunidade? | Participantes corretos? | Transcrição completa? | Análise disponível? | Revisão preservada? | CRM correto? | Duplicidade? | Permissões? | Aprovado?"}}
      ]},
      {"id":"entregar","titulo":"Entregar","objetivo":"Ativar com um grupo pequeno e tornar a qualidade parte da rotina comercial.","passos":[
        {"id":"piloto-vendedores","titulo":"Ativar com vendedores piloto","acao":"Escolha poucos vendedores e tipos de reunião, acompanhe as primeiras calls e permita voltar ao processo anterior sem perder a reunião.","concluidoQuando":"O piloto termina sem falha crítica e os vendedores revisam o pós-call dentro do tempo combinado.","entregavel":"Piloto comercial em produção.","duracao":"3–5 dias","insumos":["Dois ou três vendedores","Líder acompanhando","Critérios de pausa e sucesso"],"execucao":["Defina participantes, tipos de call, período, suporte e condições de pausa.","Observe as primeiras dez reuniões e registre atraso, falha, utilidade e taxa de revisão.","Colete discordâncias no próprio insight em vez de depender de mensagens soltas.","Compare tempo de registro, completude de próximos passos e uso do follow-up com a linha de base."],"atencao":"Não obrigue toda a equipe no primeiro dia. A confiança depende de corrigir rapidamente atribuições e tarefas erradas.","modelo":{"titulo":"Plano do piloto comercial","conteudo":"Vendedores:\nTipos de reunião:\nPeríodo:\nLinha de base:\nSuporte:\nPausar se:\nIndicadores:\nRitual diário:\nDecisão: corrigir | repetir | ampliar"}},
        {"id":"instituir-revisao","titulo":"Entregar manual e revisão semanal","acao":"Documente operação, playbook, privacidade, confirmação e contingência e deixe uma amostra semanal de qualidade sob responsabilidade do líder.","concluidoQuando":"A equipe opera, corrige e mede a solução sem o implementador e a primeira revisão tem data e dono.","entregavel":"Manual e rotina de inteligência comercial.","duracao":"60–90 min","insumos":["Dados do piloto","Acessos e responsáveis","Playbook final"],"execucao":["Documente agendamento, consentimento, sala, revisão pós-call, confirmação e correção de insight.","Entregue indicadores de uso, precisão, tarefas confirmadas, próximos passos com data e tempo economizado.","Treine o líder para revisar uma amostra, alterar o playbook e voltar uma versão.","Marque a revisão semanal e registre pendências, retenção dos dados e responsáveis por incidentes."],"atencao":"Não deixe o modelo aprender silenciosamente com toda reunião. Mudança de playbook ou prompt precisa de versão, teste e responsável.","modelo":{"titulo":"Ritual semanal de qualidade","conteudo":"Amostra de calls:\nInsights corretos por tipo:\nInsights contestados:\nTarefas confirmadas:\nPróximos passos com data:\nTempo até revisão:\nFalhas de captura:\nMudanças propostas:\nVersão testada:\nResponsável e prazo:"}}
      ]}
    ]
  }$comercial$::jsonb,
  versao = roteiro.versao + 1
from public.solucoes as projeto
where roteiro.projeto_id = projeto.id
  and projeto.slug = 'inteligencia-comercial-com-ia';

update public.projeto_roteiros as roteiro
set
  resultado = 'Uma operação contínua que transforma conhecimento da empresa em conteúdo adaptado por canal, aprovado e acompanhado por resultado.',
  cliente_ideal = 'Especialistas e empresas com conhecimento acumulado, produção irregular e dificuldade de transformar reuniões, vídeos, cases e pesquisas em conteúdo consistente.',
  entregavel_final = 'Tese editorial, voz, biblioteca de fontes, fluxo de produção, adaptações por canal, aprovação, calendário de trinta dias e rotina de análise.',
  roteiro = $conteudo${
    "fundamentos": [
      {"titulo":"Fonte antes de texto","descricao":"A operação começa na matéria-prima da empresa. O modelo organiza e redige, mas não cria experiência, case ou número."},
      {"titulo":"Uma tese, várias formas","descricao":"Adaptar por canal muda estrutura e linguagem sem trocar argumento, prova ou consequência da peça de origem."},
      {"titulo":"Publicação é decisão humana","descricao":"Toda peça preserva versão e aprovação. API de canal publica somente conteúdo explicitamente aprovado."}
    ],
    "fases": [
      {"id":"entender","titulo":"Entender","objetivo":"Definir o que a marca tem a dizer, para quem e com quais provas.","passos":[
        {"id":"definir-tese","titulo":"Definir tese, público e resultado","acao":"Escolha um público específico, a mudança de percepção desejada e de três a cinco teses que a empresa consegue sustentar com experiência ou dados.","concluidoQuando":"Cada tese tem público, afirmação, prova disponível, consequência e assunto que não será prometido.","entregavel":"Documento de tese editorial.","duracao":"60–90 min","insumos":["Posicionamento atual","Perguntas de clientes","Cases e aprendizados próprios"],"execucao":["Liste problemas sobre os quais a empresa já tem experiência concreta.","Escreva cada tese como opinião demonstrável, não como tema genérico.","Associe casos, números, demonstrações ou fontes que sustentam cada afirmação.","Defina a ação ou mudança de percepção esperada e remova teses sem prova disponível."],"atencao":"IA, inovação e produtividade são territórios, não teses. A tese precisa afirmar algo que possa ser demonstrado ou contestado.","modelo":{"titulo":"Ficha de tese editorial","conteudo":"Público:\nProblema vivido:\nTese em uma frase:\nO que prova:\nExemplo ou demonstração:\nConsequência prática:\nO que não afirmamos:\nAção desejada:"}},
        {"id":"mapear-voz-canais","titulo":"Mapear voz e papel de cada canal","acao":"Extraia padrões de materiais aprovados e defina o trabalho de cada canal, incluindo formato, frequência e passagem para a próxima etapa da jornada.","concluidoQuando":"A voz tem exemplos positivos e negativos e cada canal possui função e formatos prioritários.","entregavel":"Guia de voz e arquitetura de canais.","duracao":"60–90 min","insumos":["Dez conteúdos aprovados","Canais ativos e métricas","Pessoa que aprova a marca"],"execucao":["Marque vocabulário, tamanho de frase, grau de opinião, abertura, provas e chamadas recorrentes.","Registre palavras, promessas, estilos e assuntos que descaracterizam a marca.","Defina o papel de cada canal, como descoberta, aprofundamento, relacionamento ou conversão.","Escreva dois exemplos corretos e dois incorretos para calibrar revisão e modelo."],"atencao":"Copiar o texto de um canal para outro não é multicanal. Também não invente uma voz aspiracional que ninguém na empresa reconhece.","modelo":{"titulo":"Guia curto de voz","conteudo":"A marca soa como:\nA marca não soa como:\nFrases e ritmo:\nPalavras preferidas:\nPalavras banidas:\nComo usamos opinião:\nComo atribuímos prova:\nCTAs permitidos:\nExemplo aprovado:\nExemplo reprovado e motivo:"}}
      ]},
      {"id":"preparar","titulo":"Preparar","objetivo":"Organizar fontes, papéis e estados antes de produzir em escala.","passos":[
        {"id":"montar-biblioteca","titulo":"Montar a biblioteca de fontes","acao":"Centralize vídeos, transcrições, reuniões, cases, pesquisas e documentos em unidades pesquisáveis com origem, permissão e validade.","concluidoQuando":"As fontes prioritárias podem ser encontradas por tese e cada uma mostra autor, origem, data, permissão e revisão.","entregavel":"Biblioteca editorial rastreável.","duracao":"2–4 h","insumos":["Materiais próprios","Permissões de uso","Teses aprovadas"],"execucao":["Inventarie fontes e descarte duplicatas, rascunhos sem dono e material sem autorização.","Transcreva áudio e vídeo preservando origem, participante e horário quando relevante.","Quebre materiais por ideia e associe tese, tema, data, autor e status de uso.","Crie busca que devolva trecho e origem juntos e teste com dez perguntas editoriais reais."],"atencao":"Documento inteiro sem metadado vira contexto confuso. A unidade precisa ser pequena o bastante para citar e grande o bastante para preservar o sentido.","modelo":{"titulo":"Ficha da fonte","conteudo":"fonte_id:\nTítulo:\nTipo:\nAutor:\nOrigem ou URL:\nPublicado ou registrado em:\nPermissão de uso:\nTeses relacionadas:\nTrechos úteis:\nRestrições:\nRevisar em:"}},
        {"id":"desenhar-fluxo","titulo":"Desenhar produção e aprovação","acao":"Defina estados, papéis, critérios de passagem e o que acontece quando falta fonte, a revisão reprova ou a data de publicação muda.","concluidoQuando":"Uma pauta de teste percorre briefing, rascunho, revisão, adaptação, aprovação, agendamento e publicação sem dúvida de responsabilidade.","entregavel":"Workflow editorial e matriz de papéis.","duracao":"60–90 min","insumos":["Equipe e fornecedores envolvidos","Calendário atual","Política de aprovação"],"execucao":["Defina os estados ideia, pautada, em produção, em revisão, aprovada, agendada, publicada e arquivada.","Nomeie responsável, prazo e critério de saída para cada estado.","Separe revisão factual, revisão de voz e aprovação final para localizar divergências.","Defina reabertura de conteúdo aprovado e garanta que uma nova edição cria nova versão."],"atencao":"Aprovação por silêncio gera risco. A peça precisa de pessoa, data e versão explicitamente aprovadas.","modelo":{"titulo":"Matriz do fluxo editorial","conteudo":"Estado | Responsável | Entrada obrigatória | Ação | Critério de saída | Próximo estado | Prazo\n\nQuem aprova fatos:\nQuem aprova voz:\nQuem publica:\nComo reabrir:\nComo cancelar:"}}
      ]},
      {"id":"construir","titulo":"Construir","objetivo":"Produzir uma peça de origem forte e adaptá-la com consistência para os canais.","passos":[
        {"id":"pesquisar-produzir","titulo":"Pesquisar e produzir a peça de origem","acao":"Transforme uma tese em briefing, recupere fontes e produza a peça principal com afirmações ligadas às evidências e lacunas visíveis.","concluidoQuando":"O rascunho tem tese, prova, consequência, referências e nenhuma afirmação factual sem fonte ou validação marcada.","entregavel":"Peça de origem com fontes.","duracao":"90–150 min","insumos":["Tese escolhida","Biblioteca editorial","Formato de origem"],"execucao":["Crie briefing com público, tensão, tese, provas, estrutura, formato e ação desejada.","Recupere trechos por tese e descarte resultados que apenas repetem palavras sem sustentar a afirmação.","Gere um esqueleto e depois o rascunho, mantendo referência interna em cada número, case e citação.","Rode revisão factual e de voz separadamente e devolva lacunas para uma pessoa em vez de preenchê-las."],"atencao":"Um texto fluido pode estar vazio ou errado. Avalie primeiro tese e prova; polimento vem depois da substância.","modelo":{"titulo":"Briefing da peça de origem","conteudo":"Público:\nMomento da jornada:\nTensão real:\nTese:\nProvas e fontes:\nDemonstração:\nEstrutura:\nFormato:\nTom:\nO que evitar:\nAção desejada:\nCritério de aprovação:"}},
        {"id":"adaptar-agendar","titulo":"Adaptar por canal e montar o calendário","acao":"Derive versões que respeitam o papel, o espaço e o comportamento de cada canal, mantendo o mesmo núcleo factual e o vínculo com a origem.","concluidoQuando":"Cada adaptação preserva tese e prova, passa no preview do canal e está ligada à versão aprovada da origem.","entregavel":"Pacote multicanal pronto para aprovação.","duracao":"90–150 min","insumos":["Peça de origem revisada","Arquitetura de canais","Templates reais de cada canal"],"execucao":["Identifique o núcleo que não pode mudar: afirmação, prova, consequência e ação.","Reestruture abertura, extensão, ritmo e mídia conforme o papel de cada canal.","Gere preview com quebras, links, mídia, alt text e limites reais antes da aprovação.","Associe cada versão à origem, data, campanha e métrica e envie o pacote para aprovação final."],"atencao":"Não deixe a adaptação acrescentar exemplo, número ou promessa que não existe na peça aprovada.","modelo":{"titulo":"Matriz de adaptação","conteudo":"Canal | Papel | Gancho | Estrutura | Limite | Mídia | CTA | Origem | Versão | Métrica\nLinkedIn | aprofundar | ...\nInstagram | descobrir | ...\nE-mail | relacionar | ...\nBlog | capturar busca | ..."}}
      ]},
      {"id":"validar","titulo":"Validar","objetivo":"Provar aderência, correção e qualidade visual antes de publicar.","passos":[
        {"id":"revisar-lote","titulo":"Revisar dez peças às cegas","acao":"Misture peças humanas, assistidas e inadequadas e peça ao aprovador para avaliar voz, especificidade, prova e utilidade sem saber a origem.","concluidoQuando":"Os desvios recorrentes foram identificados e prompt, guia ou fluxo foi corrigido com novo teste.","entregavel":"Relatório de aderência editorial.","duracao":"60–90 min","insumos":["Dez peças variadas","Rubrica de avaliação","Aprovador da marca"],"execucao":["Prepare as peças sem rótulo de origem e garanta variedade de teses e formatos.","Avalie tese clara, especificidade, voz, prova, consequência, genericidade e risco factual.","Compare notas e comentários para descobrir padrões, não apenas preferência por uma frase.","Corrija fonte, briefing, prompt ou guia conforme a causa e repita as peças reprovadas."],"atencao":"Perguntar apenas se gostou transforma validação em gosto. A rubrica precisa mostrar exatamente por que uma peça está pronta.","modelo":{"titulo":"Rubrica editorial","conteudo":"Peça | Tese clara 0–2 | Prova 0–2 | Voz 0–2 | Especificidade 0–2 | Utilidade 0–2 | Risco factual | Trecho genérico | Ajuste | Aprovado?"}},
        {"id":"validar-canais","titulo":"Validar preview, aprovação e publicação","acao":"Teste o pacote no tamanho real dos canais, reprove uma versão, altere a origem e confirme que somente a versão final aprovada pode ser publicada.","concluidoQuando":"Nenhuma peça cortada, desatualizada ou não aprovada chega ao agendamento e a publicação retorna URL e horário reais.","entregavel":"Aceite multicanal ponta a ponta.","duracao":"60–120 min","insumos":["Contas ou ambientes de teste","Pacote multicanal","Aprovador e publicador"],"execucao":["Abra cada peça em viewport ou preview real e confira cortes, quebras, contraste, links e acessibilidade.","Reprove uma adaptação e confirme que as demais não liberam a peça rejeitada por engano.","Edite a origem aprovada e valide que as adaptações dependentes voltam para revisão.","Publique uma peça de teste autorizada e guarde identificador, URL, horário, canal e versão."],"atencao":"Status agendado não prova publicação. A entrega precisa confirmar o objeto no canal e registrar falha quando ele não existir.","modelo":{"titulo":"Checklist de publicação","conteudo":"[ ] copy dentro do limite\n[ ] mídia e proporção corretas\n[ ] alt text\n[ ] links testados\n[ ] origem e versão\n[ ] aprovação com pessoa e data\n[ ] agendamento correto\n[ ] URL publicada confirmada\n[ ] falha visível e repetível"}}
      ]},
      {"id":"entregar","titulo":"Entregar","objetivo":"Entregar trinta dias de conteúdo e tornar o ciclo repetível e mensurável.","passos":[
        {"id":"calendario-trinta-dias","titulo":"Montar trinta dias de conteúdo","acao":"Distribua teses, formatos e canais num calendário realista, com fontes e aprovações, sem preencher todas as datas apenas para parecer completo.","concluidoQuando":"O calendário tem cadência executável, peças aprovadas para a primeira semana e backlog com fontes para as seguintes.","entregavel":"Calendário editorial de trinta dias.","duracao":"2–4 h","insumos":["Pacotes validados","Datas e eventos reais","Capacidade da equipe"],"execucao":["Defina uma cadência que a equipe consegue revisar e sustentar após a entrega.","Equilibre teses e momentos da jornada sem obrigar o mesmo volume em todos os canais.","Ligue cada item a briefing, fonte, responsável, versão e aprovação.","Deixe a primeira semana pronta e as demais com material suficiente para produzir sem começar do zero."],"atencao":"Calendário lotado não é operação saudável. Proteja espaço para fato novo, reação, pausa e aprendizado de desempenho.","modelo":{"titulo":"Calendário de trinta dias","conteudo":"Data | Tese | Peça de origem | Canal | Formato | Fonte | Responsável | Estado | Aprovação | URL | Métrica\n\nCadência por canal:\nCapacidade semanal:\nEspaços livres para oportunidade:"}},
        {"id":"entregar-operacao","titulo":"Entregar rotina e leitura de resultado","acao":"Treine pesquisa, produção, aprovação, publicação e análise e marque o primeiro ciclo em que o cliente executará sem o implementador.","concluidoQuando":"A equipe produz e aprova um novo pacote usando o manual e consegue relacionar desempenho com tese, formato e canal.","entregavel":"Manual da operação multicanal.","duracao":"60–90 min","insumos":["Calendário final","Acessos e responsáveis","Métricas dos canais"],"execucao":["Documente o caminho completo com papéis, prazos, versões, contingência e critérios de aprovação.","Treine a equipe criando uma pauta nova, reprovando uma peça e publicando uma versão de teste.","Defina indicadores por objetivo do canal e evite comparar métricas diferentes como se fossem iguais.","Marque a revisão mensal para decidir o que manter, parar, aprofundar ou testar."],"atencao":"A IA não substitui a decisão editorial. O cliente precisa saber escolher tese, rejeitar genericidade e interromper uma linha que não produz valor.","modelo":{"titulo":"Ritual mensal editorial","conteudo":"Teses publicadas:\nPeças por canal:\nResultados por objetivo:\nConteúdos com prova forte:\nConteúdos genéricos ou fracos:\nPerguntas recebidas:\nO que manter:\nO que parar:\nO que aprofundar:\nPróximo teste:\nResponsáveis e datas:"}}
      ]}
    ]
  }$conteudo$::jsonb,
  versao = roteiro.versao + 1
from public.solucoes as projeto
where roteiro.projeto_id = projeto.id
  and projeto.slug = 'operacao-conteudo-multicanal';

-- O Radar é deliberadamente menor: uma tarefa por fase, cinco no total. Ele é
-- a primeira vitória indicada para quem ainda não entregou um projeto técnico.
update public.projeto_roteiros as roteiro
set
  resultado = 'Uma pesquisa de satisfação simples que coleta notas e comentários, mostra os temas recorrentes e alerta a equipe para recuperar clientes insatisfeitos.',
  cliente_ideal = 'Empresas com uma base de clientes identificada que hoje recebem feedback de forma dispersa ou descobrem a insatisfação somente no cancelamento.',
  entregavel_final = 'Pesquisa ativa, base de respostas, classificação dos comentários, alerta de detratores, painel, primeiro relatório e rotina de fechamento do retorno.',
  roteiro = $satisfacao${
    "fundamentos": [
      {"titulo":"Perguntar para agir","descricao":"A pesquisa só existe quando cada faixa de resposta tem uma ação e uma pessoa responsável pelo retorno."},
      {"titulo":"Comentário não é diagnóstico","descricao":"A IA organiza o que foi dito e preserva o trecho. Ela não inventa causa, intenção ou solução para o cliente."},
      {"titulo":"Pouco e bem fechado","descricao":"Uma pergunta principal e um comentário útil valem mais que um questionário longo que ninguém conclui."}
    ],
    "fases": [
      {"id":"entender","titulo":"Entender","objetivo":"Escolher o momento, a pergunta e a ação que a empresa conseguirá sustentar.","passos":[
        {"id":"desenhar-pesquisa","titulo":"Desenhar a pesquisa e a recuperação","acao":"Escolha NPS ou CSAT, defina um único momento da jornada e escreva o que acontece com nota baixa, neutra e alta.","concluidoQuando":"A pesquisa tem pergunta, escala, comentário, gatilho, público, responsável e prazo de retorno aprovados.","entregavel":"Plano de pesquisa e fechamento do retorno.","duracao":"45–60 min","insumos":["Um momento claro da jornada","Lista de clientes elegíveis","Pessoa responsável por responder"],"execucao":["Escolha NPS para relação ou CSAT para uma interação específica e não misture os dois objetivos.","Escreva uma pergunta principal, um campo aberto e, se necessário, uma pergunta curta de contexto.","Defina quem recebe nota baixa, em quanto tempo responde e como registra o desfecho.","Escolha data, público, canal, limite de lembretes e condições de exclusão ou opt-out."],"atencao":"Não envie pesquisa se ninguém puder responder aos detratores. Coletar crítica e ignorá-la piora a experiência.","modelo":{"titulo":"Plano da pesquisa","conteudo":"Objetivo:\nMétodo: NPS | CSAT\nMomento da jornada:\nPúblico elegível:\nPergunta principal:\nCampo de comentário:\nCanal:\nData:\nLembretes:\nNota baixa: responsável, prazo e ação\nNota neutra: responsável e ação\nNota alta: responsável e ação\nOpt-out:"}}
      ]},
      {"id":"preparar","titulo":"Preparar","objetivo":"Organizar a base, o formulário e o canal sem criar um projeto grande.","passos":[
        {"id":"preparar-base-canal","titulo":"Preparar contatos, formulário e envio","acao":"Importe somente clientes elegíveis, crie um link individual de resposta e prepare uma mensagem curta com identificação, motivo e opt-out.","concluidoQuando":"Dez contatos de teste recebem links únicos, respondem uma vez e aparecem na campanha correta sem expor respostas de outra pessoa.","entregavel":"Campanha pronta para teste.","duracao":"90–150 min","insumos":["CSV ou CRM com clientes elegíveis","Identidade do remetente","Plano aprovado"],"execucao":["Limpe duplicatas, contatos sem base legítima e pessoas que já pediram para não receber mensagens.","Crie campanha, destinatário e token aleatório; o link não deve revelar e-mail, telefone ou identificador sequencial.","Monte formulário responsivo com escala acessível, comentário opcional e confirmação clara.","Envie para dez endereços internos e teste entrega, resposta repetida, link inválido e opt-out."],"atencao":"Não coloque dados do cliente na URL. Um token deve identificar a resposta no servidor sem expor a pessoa.","modelo":{"titulo":"CSV mínimo da campanha","conteudo":"cliente_id,nome,email_ou_telefone,momento_da_jornada,ocorrido_em,responsavel,consentimento_status\n\nMensagem:\nOlá, [nome]. Queremos entender como foi [momento]. Leva menos de um minuto: [link]. Se não quiser receber esta pesquisa, use [opt-out]."}}
      ]},
      {"id":"construir","titulo":"Construir","objetivo":"Coletar, organizar e alertar sem automatizar a resposta ao cliente.","passos":[
        {"id":"coletar-analisar-alertar","titulo":"Coletar respostas e alertar a equipe","acao":"Grave nota e comentário, classifique temas com evidência, atualize o painel e crie tarefa humana imediata para respostas críticas.","concluidoQuando":"Uma resposta crítica gera alerta e tarefa com comentário, responsável e prazo; o painel atualiza sem duplicar resposta.","entregavel":"Radar de satisfação funcionando.","duracao":"3–5 h","insumos":["Campanha de teste","Banco e painel","Responsáveis definidos","Chave de IA no servidor"],"execucao":["Valide token, campanha e estado antes de aceitar a resposta e impeça duplicidade conforme a regra aprovada.","Grave nota e comentário originais antes de chamar a IA para que nenhuma falha perca o feedback.","Classifique tema, urgência e sentimento com trecho de evidência e mantenha desconhecido quando faltar contexto.","Para nota ou termo crítico, crie alerta e tarefa humana; gere apenas um rascunho de retorno para revisão."],"atencao":"Nunca envie pedido de desculpas, desconto ou promessa automaticamente. O comentário pode exigir contexto que apenas a equipe possui.","modelo":{"titulo":"Registro da resposta","conteudo":"resposta_id:\ncampanha_id:\ncliente_id:\nnota:\ncomentario_original:\ntema:\nurgencia:\nsentimento:\ntrecho_evidencia:\nrecebido_em:\nalerta_id:\nresponsavel:\nprazo_retorno:\nstatus_fechamento:"}}
      ]},
      {"id":"validar","titulo":"Validar","objetivo":"Testar o radar com poucas pessoas antes de convidar clientes reais.","passos":[
        {"id":"rodar-piloto","titulo":"Rodar um piloto de dez respostas","acao":"Simule notas, comentários, ausência de texto, link repetido e falha de envio; depois convide um grupo pequeno autorizado e acompanhe cada retorno.","concluidoQuando":"Classificação, painel, alerta e fechamento funcionam e nenhuma resposta crítica fica sem responsável além do prazo.","entregavel":"Piloto de satisfação aprovado.","duracao":"60–90 min","insumos":["Dez respostas simuladas","Grupo pequeno de clientes","Responsável disponível"],"execucao":["Crie respostas positivas, neutras, críticas, ambíguas, sem comentário e com palavras urgentes.","Compare classificação e trecho com leitura humana e corrija regras que gerem falso alerta ou omissão.","Teste e-mail devolvido, opt-out, link inválido e resposta repetida sem perder o estado da campanha.","Envie ao grupo piloto, acompanhe alertas ao vivo e registre cada contato e desfecho."],"atencao":"Taxa de resposta do piloto não representa toda a base. Valide o funcionamento e a compreensão da pergunta antes de interpretar tendência.","modelo":{"titulo":"Matriz do piloto","conteudo":"Caso | Nota | Comentário | Tema esperado | Urgência esperada | Deve alertar? | Resultado real | Responsável recebeu? | Retorno fechado? | Aprovado? | Correção"}}
      ]},
      {"id":"entregar","titulo":"Entregar","objetivo":"Ativar a primeira campanha e deixar uma rotina pequena e clara.","passos":[
        {"id":"ativar-entregar","titulo":"Ativar, fechar retornos e entregar o relatório","acao":"Envie a primeira campanha, acompanhe respostas e retornos e entregue um resumo que separa números, temas, exemplos e próximas ações.","concluidoQuando":"A campanha encerrou, todos os alertas têm desfecho e a equipe consegue criar a próxima usando o manual.","entregavel":"Primeiro relatório e manual do radar.","duracao":"1–2 dias acompanhados","insumos":["Piloto aprovado","Base final","Responsáveis e prazos","Data de encerramento"],"execucao":["Congele público e versão da pergunta, revise remetente e envie em lote controlado.","Acompanhe entrega, resposta, opt-out e alertas sem adicionar lembretes além do combinado.","Confirme que cada nota crítica recebeu contato e registre desfecho, pendência ou tentativa sem resposta.","Entregue relatório com base, taxa, distribuição, temas, exemplos anonimizados e ações com dono e prazo."],"atencao":"Não apresente NPS ou média sem tamanho da base, número de respostas e período. Poucas respostas são sinal, não verdade definitiva.","modelo":{"titulo":"Relatório da campanha","conteudo":"Período:\nBase convidada:\nEntregues:\nRespostas:\nTaxa de resposta:\nOpt-outs:\nDistribuição de notas:\nNPS ou CSAT:\nTemas por ocorrência:\nExemplos anonimizados:\nAlertas abertos e fechados:\nAprendizados:\nAções, donos e prazos:\nPróxima campanha:"}}
      ]}
    ]
  }$satisfacao$::jsonb,
  versao = roteiro.versao + 1
from public.solucoes as projeto
where roteiro.projeto_id = projeto.id
  and projeto.slug = 'radar-satisfacao-com-ia';

commit;
